# Generated by Django 5.2.4 on 2026-03-05 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cit_id', models.AutoField(db_column='CIT_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('fecha_cita', models.DateField(db_column='FECHA_CITA')),
                ('hora_inicio', models.TimeField(db_column='HORA_INICIO')),
                ('hora_fin', models.TimeField(db_column='HORA_FIN')),
                ('duracion_min', models.SmallIntegerField(db_column='DURACION_MIN', default=30)),
                ('tipo_cita', models.CharField(choices=[('CONSULTA', 'Consulta General'), ('SEGUIMIENTO', 'Seguimiento'), ('URGENCIA', 'Urgencia'), ('PROCEDIMIENTO', 'Procedimiento'), ('CHEQUEO', 'Chequeo General')], db_column='TIPO_CITA', max_length=30)),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=500)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], db_column='ESTADO', default='PROGRAMADA', max_length=30)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('PREFERENTE', 'Preferente'), ('URGENTE', 'Urgente')], db_column='PRIORIDAD', default='NORMAL', max_length=20)),
                ('sala', models.CharField(blank=True, db_column='SALA', default='', max_length=50)),
                ('notas_medico', models.TextField(blank=True, db_column='NOTAS_MEDICO', default='')),
                ('notas_admin', models.CharField(blank=True, db_column='NOTAS_ADMIN', default='', max_length=500)),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='MOTIVO_CANCELACION', default='', max_length=500)),
                ('cancelada_en', models.DateTimeField(blank=True, db_column='CANCELADA_EN', null=True)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('cancelada_por', models.ForeignKey(blank=True, db_column='CANCELADA_POR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(db_column='MEDICO_ID', on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='patients.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'CIT_CITAS',
                'ordering': ['fecha_cita', 'hora_inicio'],
                'unique_together': {('hospital_id', 'medico', 'fecha_cita', 'hora_inicio')},
            },
        ),
    ]
