# Generated by Django 5.2.4 on 2026-03-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('pro_id', models.AutoField(db_column='PRO_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('codigo', models.CharField(blank=True, db_column='CODIGO', default='', max_length=50)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=200)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', default='', max_length=500)),
                ('categoria', models.CharField(choices=[('MATERIAL_MEDICO', 'Material Médico'), ('INSUMO_QUIRURGICO', 'Insumo Quirúrgico'), ('LIMPIEZA', 'Limpieza / Higiene'), ('OFICINA', 'Oficina / Administrativo'), ('EQUIPO', 'Equipo / Herramienta'), ('ALIMENTACION', 'Alimentación'), ('OTRO', 'Otro')], db_column='CATEGORIA', default='MATERIAL_MEDICO', max_length=30)),
                ('unidad_medida', models.CharField(db_column='UNIDAD_MEDIDA', default='unidad', max_length=30)),
                ('stock_actual', models.DecimalField(db_column='STOCK_ACTUAL', decimal_places=3, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(db_column='STOCK_MINIMO', decimal_places=3, default=0, max_digits=12)),
                ('stock_maximo', models.DecimalField(blank=True, db_column='STOCK_MAXIMO', decimal_places=3, max_digits=12, null=True)),
                ('precio_unitario', models.DecimalField(db_column='PRECIO_UNITARIO', decimal_places=4, default=0, max_digits=12)),
                ('proveedor', models.CharField(blank=True, db_column='PROVEEDOR', default='', max_length=200)),
                ('ubicacion', models.CharField(blank=True, db_column='UBICACION', default='', max_length=100)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'BOD_PRODUCTOS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('mov_id', models.AutoField(db_column='MOV_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('BAJA', 'Baja / Descarte')], db_column='TIPO_MOVIMIENTO', max_length=20)),
                ('cantidad', models.DecimalField(db_column='CANTIDAD', decimal_places=3, max_digits=12)),
                ('cantidad_anterior', models.DecimalField(db_column='CANTIDAD_ANTERIOR', decimal_places=3, max_digits=12)),
                ('cantidad_posterior', models.DecimalField(db_column='CANTIDAD_POSTERIOR', decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(blank=True, db_column='MOTIVO', default='', max_length=500)),
                ('referencia', models.CharField(blank=True, db_column='REFERENCIA', default='', max_length=200)),
                ('departamento', models.CharField(blank=True, db_column='DEPARTAMENTO', default='', max_length=100)),
                ('proveedor', models.CharField(blank=True, db_column='PROVEEDOR', default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(db_column='PRO_ID', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='warehouse.producto')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'BOD_MOVIMIENTOS',
                'ordering': ['-created_at'],
            },
        ),
    ]
