-- =============================================================
-- HealthTech Solutions — DDL: PAC_PACIENTES
-- Módulo M02 — Registro de Pacientes
-- Compatible: Oracle 19c RAC + Oracle 21c XE
--
-- PHI (Protected Health Information) → tablespace PHI_DATA
-- VPD: columna HOSPITAL_ID en TODAS las tablas PAC_
-- Soft delete: columna ACTIVO (sin DELETE físico)
-- =============================================================

-- ------------------------------------------------------------
-- Tabla principal de pacientes
-- ------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE PAC_PACIENTES (
      PAC_ID               NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          CONSTRAINT PK_PAC_PACIENTES PRIMARY KEY,
      HOSPITAL_ID          NUMBER         NOT NULL,

      -- Número de expediente único por hospital
      NO_EXPEDIENTE        VARCHAR2(30)   NOT NULL,

      -- Datos de identificación (PHI)
      PRIMER_NOMBRE        VARCHAR2(100)  NOT NULL,
      SEGUNDO_NOMBRE       VARCHAR2(100)  DEFAULT '''' '''',
      PRIMER_APELLIDO      VARCHAR2(100)  NOT NULL,
      SEGUNDO_APELLIDO     VARCHAR2(100)  DEFAULT '''' '''',
      NOMBRE_CASADA        VARCHAR2(100)  DEFAULT '''' '''',

      -- Documento de identidad
      TIPO_DOCUMENTO       VARCHAR2(20)   NOT NULL,
      NO_DOCUMENTO         VARCHAR2(30)   NOT NULL,

      -- Datos demográficos
      FECHA_NACIMIENTO     DATE           NOT NULL,
      SEXO                 CHAR(1)        NOT NULL,
      ESTADO_CIVIL         VARCHAR2(20)   DEFAULT ''''SOLTERO'''',
      NACIONALIDAD         VARCHAR2(50)   DEFAULT ''''GUATEMALTECA'''',

      -- Datos de contacto (PHI)
      DIRECCION            VARCHAR2(500)  DEFAULT '''' '''',
      MUNICIPIO            VARCHAR2(100)  DEFAULT '''' '''',
      DEPARTAMENTO         VARCHAR2(100)  DEFAULT '''' '''',
      TELEFONO_PRINCIPAL   VARCHAR2(20)   DEFAULT '''' '''',
      TELEFONO_ALTERNATIVO VARCHAR2(20)   DEFAULT '''' '''',
      EMAIL                VARCHAR2(150)  DEFAULT '''' '''',

      -- Seguro / cobertura
      TIPO_PACIENTE        VARCHAR2(30)   DEFAULT ''''GENERAL'''',
      NO_AFILIACION        VARCHAR2(50)   DEFAULT '''' '''',
      ASEGURADORA          VARCHAR2(100)  DEFAULT '''' '''',

      -- Datos médicos relevantes
      GRUPO_SANGUINEO      VARCHAR2(5)    DEFAULT '''' '''',
      FACTOR_RH            CHAR(1)        DEFAULT '''' '''',
      PESO_KG              NUMBER(5,2)    DEFAULT NULL,
      TALLA_CM             NUMBER(5,1)    DEFAULT NULL,

      -- Imagen perfil (PACS / S3)
      FOTO_S3_KEY          VARCHAR2(500)  DEFAULT '''' '''',

      -- Médico de cabecera
      MEDICO_ID            NUMBER         DEFAULT NULL,

      -- Estado y auditoría
      ACTIVO               NUMBER(1)      DEFAULT 1   NOT NULL,
      CREATED_BY           NUMBER         DEFAULT NULL,
      CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_BY           NUMBER         DEFAULT NULL,
      UPDATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

      -- Restricciones
      CONSTRAINT CHK_PAC_SEXO        CHECK (SEXO IN (''''M'''', ''''F'''')),
      CONSTRAINT CHK_PAC_TIPO_DOC    CHECK (TIPO_DOCUMENTO IN (
                                       ''''DPI'''', ''''PASAPORTE'''', ''''CUI'''', ''''CEDULA'''', ''''OTRO'''')),
      CONSTRAINT CHK_PAC_TIPO_PAC    CHECK (TIPO_PACIENTE IN (
                                       ''''GENERAL'''', ''''IGSS'''', ''''PRIVADO'''',
                                       ''''SEGURO'''', ''''EXTERIOR'''', ''''OTRO'''')),
      CONSTRAINT CHK_PAC_ESTADO_CIVIL CHECK (ESTADO_CIVIL IN (
                                       ''''SOLTERO'''', ''''CASADO'''', ''''UNION_LIBRE'''',
                                       ''''DIVORCIADO'''', ''''VIUDO'''')),
      CONSTRAINT CHK_PAC_ACTIVO      CHECK (ACTIVO IN (0, 1))
    ) TABLESPACE PHI_DATA
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Expediente único por hospital
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE PAC_PACIENTES
    ADD CONSTRAINT UQ_PAC_EXPEDIENTE UNIQUE (HOSPITAL_ID, NO_EXPEDIENTE)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2261 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Documento único por hospital
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE PAC_PACIENTES
    ADD CONSTRAINT UQ_PAC_DOCUMENTO UNIQUE (HOSPITAL_ID, TIPO_DOCUMENTO, NO_DOCUMENTO)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2261 THEN NULL; ELSE RAISE; END IF;
END;
/

-- FK: Hospital
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE PAC_PACIENTES
    ADD CONSTRAINT FK_PAC_HOSPITAL
      FOREIGN KEY (HOSPITAL_ID) REFERENCES SEC_HOSPITALES(HOSPITAL_ID)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2275 THEN NULL; ELSE RAISE; END IF;
END;
/

-- FK: Médico creador (Usuario)
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE PAC_PACIENTES
    ADD CONSTRAINT FK_PAC_MEDICO
      FOREIGN KEY (MEDICO_ID) REFERENCES SEC_USUARIOS(USR_ID)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2275 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Índices de búsqueda frecuente
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PAC_HOSPITAL    ON PAC_PACIENTES(HOSPITAL_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PAC_APELLIDO    ON PAC_PACIENTES(HOSPITAL_ID, PRIMER_APELLIDO, SEGUNDO_APELLIDO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PAC_DOCUMENTO   ON PAC_PACIENTES(HOSPITAL_ID, NO_DOCUMENTO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PAC_FECHANAC    ON PAC_PACIENTES(HOSPITAL_ID, FECHA_NACIMIENTO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- Trigger UPDATED_AT
BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER TRG_PAC_PACIENTES_UPD
    BEFORE UPDATE ON PAC_PACIENTES
    FOR EACH ROW
    BEGIN
      :NEW.UPDATED_AT := SYSTIMESTAMP;
    END;
  ';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Comentarios de columnas (documentación Oracle)
COMMENT ON TABLE  PAC_PACIENTES                     IS 'Registro maestro de pacientes (PHI - datos protegidos HIPAA)';
COMMENT ON COLUMN PAC_PACIENTES.HOSPITAL_ID         IS 'Partición VPD — aislamiento multi-hospital';
COMMENT ON COLUMN PAC_PACIENTES.NO_EXPEDIENTE       IS 'Número de expediente clínico único por hospital';
COMMENT ON COLUMN PAC_PACIENTES.TIPO_DOCUMENTO      IS 'DPI | PASAPORTE | CUI | CEDULA | OTRO';
COMMENT ON COLUMN PAC_PACIENTES.TIPO_PACIENTE       IS 'Clasificación de cobertura: GENERAL | IGSS | PRIVADO | SEGURO | EXTERIOR | OTRO';
COMMENT ON COLUMN PAC_PACIENTES.FOTO_S3_KEY         IS 'Clave S3 de la fotografía (no URL directa — usar pre-signed URL)';
