-- =============================================================
-- HealthTech Solutions — DDL: Módulo Citas (M03)
-- Tabla: CIT_CITAS
-- Tablespace: PHI_DATA (datos PHI — TDE en PROD)
-- VPD: columna HOSPITAL_ID presente para filtrado automático
-- Soft-delete: columna ACTIVO — nunca DELETE físico
-- =============================================================

-- Tabla principal de citas médicas
CREATE TABLE CIT_CITAS (
    CIT_ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    HOSPITAL_ID          NUMBER        NOT NULL,
    PAC_ID               NUMBER        NOT NULL,
    MEDICO_ID            NUMBER        NOT NULL,

    -- Horario
    FECHA_CITA           DATE          NOT NULL,
    HORA_INICIO          VARCHAR2(5)   NOT NULL,   -- 'HH24:MI', e.g. '08:30'
    HORA_FIN             VARCHAR2(5)   NOT NULL,   -- 'HH24:MI', e.g. '09:00'
    DURACION_MIN         NUMBER(3)     DEFAULT 30  NOT NULL,

    -- Tipo y estado
    TIPO_CITA            VARCHAR2(30)  NOT NULL,
    MOTIVO               VARCHAR2(500) NOT NULL,
    ESTADO               VARCHAR2(30)  DEFAULT 'PROGRAMADA' NOT NULL,
    PRIORIDAD            VARCHAR2(20)  DEFAULT 'NORMAL'     NOT NULL,

    -- Logística
    SALA                 VARCHAR2(50),

    -- Notas clínicas (PHI)
    NOTAS_MEDICO         NCLOB,
    NOTAS_ADMIN          VARCHAR2(500),

    -- Cancelación
    MOTIVO_CANCELACION   VARCHAR2(500),
    CANCELADA_POR        NUMBER,
    CANCELADA_EN         TIMESTAMP,

    -- Estado y auditoría
    ACTIVO               NUMBER(1)     DEFAULT 1   NOT NULL,
    CREATED_BY           NUMBER,
    CREATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY           NUMBER,
    UPDATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    -- ── Constraints ───────────────────────────────────────────
    CONSTRAINT CK_CIT_TIPO_CITA   CHECK (TIPO_CITA  IN ('CONSULTA','SEGUIMIENTO','URGENCIA','PROCEDIMIENTO','CHEQUEO')),
    CONSTRAINT CK_CIT_ESTADO      CHECK (ESTADO     IN ('PROGRAMADA','CONFIRMADA','EN_PROGRESO','COMPLETADA','CANCELADA','NO_ASISTIO')),
    CONSTRAINT CK_CIT_PRIORIDAD   CHECK (PRIORIDAD  IN ('NORMAL','PREFERENTE','URGENTE')),
    CONSTRAINT CK_CIT_ACTIVO      CHECK (ACTIVO     IN (0, 1)),
    CONSTRAINT CK_CIT_DURACION    CHECK (DURACION_MIN BETWEEN 5 AND 480),

    -- Unicidad: un médico no puede tener dos citas en el mismo horario (anti-doble booking)
    CONSTRAINT UQ_CIT_MEDICO_HORARIO UNIQUE (HOSPITAL_ID, MEDICO_ID, FECHA_CITA, HORA_INICIO),

    -- Claves foráneas
    CONSTRAINT FK_CIT_HOSPITAL  FOREIGN KEY (HOSPITAL_ID)   REFERENCES SEC_HOSPITALES(HOSPITAL_ID),
    CONSTRAINT FK_CIT_PACIENTE  FOREIGN KEY (PAC_ID)        REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_CIT_MEDICO    FOREIGN KEY (MEDICO_ID)     REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIT_CANCEL_BY FOREIGN KEY (CANCELADA_POR) REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIT_CREATED   FOREIGN KEY (CREATED_BY)    REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIT_UPDATED   FOREIGN KEY (UPDATED_BY)    REFERENCES SEC_USUARIOS(USR_ID)
) TABLESPACE PHI_DATA;

-- ── Índices para búsquedas frecuentes ─────────────────────────
-- Búsquedas por hospital (VPD base)
CREATE INDEX IDX_CIT_HOSPITAL  ON CIT_CITAS(HOSPITAL_ID) TABLESPACE PHI_DATA;

-- Agenda diaria/semanal por hospital
CREATE INDEX IDX_CIT_FECHA     ON CIT_CITAS(HOSPITAL_ID, FECHA_CITA, ESTADO) TABLESPACE PHI_DATA;

-- Agenda del médico
CREATE INDEX IDX_CIT_MEDICO    ON CIT_CITAS(HOSPITAL_ID, MEDICO_ID, FECHA_CITA) TABLESPACE PHI_DATA;

-- Historial de citas por paciente
CREATE INDEX IDX_CIT_PACIENTE  ON CIT_CITAS(HOSPITAL_ID, PAC_ID, FECHA_CITA) TABLESPACE PHI_DATA;

-- Filtro por estado (colas de trabajo)
CREATE INDEX IDX_CIT_ESTADO    ON CIT_CITAS(HOSPITAL_ID, ESTADO, FECHA_CITA) TABLESPACE PHI_DATA;

-- ── Trigger UPDATED_AT ────────────────────────────────────────
CREATE OR REPLACE TRIGGER TRG_CIT_CITAS_UPD
    BEFORE UPDATE ON CIT_CITAS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ── Comentarios de columnas (documentación en catálogo Oracle) ─
COMMENT ON TABLE  CIT_CITAS                    IS 'M03 - Citas médicas programadas. PHI — VPD por HOSPITAL_ID.';
COMMENT ON COLUMN CIT_CITAS.CIT_ID             IS 'Identificador único de la cita (IDENTITY).';
COMMENT ON COLUMN CIT_CITAS.HOSPITAL_ID        IS 'Columna VPD — particionamiento lógico por hospital.';
COMMENT ON COLUMN CIT_CITAS.PAC_ID             IS 'FK a PAC_PACIENTES — paciente de la cita.';
COMMENT ON COLUMN CIT_CITAS.MEDICO_ID          IS 'FK a SEC_USUARIOS — médico asignado.';
COMMENT ON COLUMN CIT_CITAS.HORA_INICIO        IS 'Hora de inicio en formato HH24:MI (e.g. 08:30).';
COMMENT ON COLUMN CIT_CITAS.HORA_FIN           IS 'Hora de fin en formato HH24:MI (e.g. 09:00).';
COMMENT ON COLUMN CIT_CITAS.TIPO_CITA          IS 'CONSULTA|SEGUIMIENTO|URGENCIA|PROCEDIMIENTO|CHEQUEO.';
COMMENT ON COLUMN CIT_CITAS.ESTADO             IS 'PROGRAMADA|CONFIRMADA|EN_PROGRESO|COMPLETADA|CANCELADA|NO_ASISTIO.';
COMMENT ON COLUMN CIT_CITAS.PRIORIDAD          IS 'NORMAL|PREFERENTE|URGENTE.';
COMMENT ON COLUMN CIT_CITAS.NOTAS_MEDICO       IS 'Notas clínicas del médico (PHI). NCLOB para texto largo.';
COMMENT ON COLUMN CIT_CITAS.ACTIVO             IS '1=Activo, 0=Soft-delete (HIPAA: sin borrado físico de PHI).';
COMMENT ON COLUMN CIT_CITAS.CANCELADA_POR      IS 'FK a SEC_USUARIOS — quién canceló la cita.';
