-- ============================================================
-- HealthTech Solutions — DDL: Módulo Emergencias (M04)
-- Tabla: EMG_EMERGENCIAS
-- Tablespace PHI_DATA (TDE habilitado en PROD Oracle 19c)
-- VPD: HOSPITAL_ID columna de particionamiento
-- Soft-delete: ACTIVO NUMBER(1) — nunca DELETE físico (HIPAA)
-- ============================================================

-- Tabla principal de registros de emergencia
CREATE TABLE EMG_EMERGENCIAS (
    EMG_ID          NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                    CONSTRAINT PK_EMG_EMERGENCIAS PRIMARY KEY,
    HOSPITAL_ID     NUMBER          NOT NULL,

    -- Relaciones
    PAC_ID          NUMBER          NOT NULL,
    MEDICO_ID       NUMBER,                         -- nullable: puede no estar asignado al ingresar
    ENFERMERO_ID    NUMBER,                         -- nullable: enfermero que realizó triaje

    -- Registro de ingreso
    FECHA_INGRESO   DATE            NOT NULL,
    HORA_INGRESO    VARCHAR2(5)     NOT NULL,        -- 'HH24:MI'
    MOTIVO_CONSULTA VARCHAR2(500)   NOT NULL,

    -- Triaje (Manchester Triage System)
    NIVEL_TRIAJE    VARCHAR2(20)    NOT NULL
                        CONSTRAINT CHK_EMG_TRIAJE CHECK (
                            NIVEL_TRIAJE IN ('ROJO','NARANJA','AMARILLO','VERDE','AZUL')
                        ),

    -- Signos vitales al ingreso
    PRESION_SISTOLICA   NUMBER(3),                  -- mmHg
    PRESION_DIASTOLICA  NUMBER(3),                  -- mmHg
    FRECUENCIA_CARDIACA NUMBER(3),                  -- lpm
    FRECUENCIA_RESP     NUMBER(2),                  -- rpm
    TEMPERATURA         NUMBER(4,1),                -- °C
    SATURACION_O2       NUMBER(3),                  -- %
    GLUCOSA             NUMBER(4),                  -- mg/dL (opcional)
    PESO_KG             NUMBER(5,2),                -- kg (opcional)

    -- Estado y evolución
    ESTADO          VARCHAR2(30)    NOT NULL    DEFAULT 'ESPERA'
                        CONSTRAINT CHK_EMG_ESTADO CHECK (
                            ESTADO IN ('ESPERA','EN_ATENCION','OBSERVACION',
                                       'ALTA','TRANSFERIDO','FALLECIDO')
                        ),

    -- Diagnóstico y tratamiento
    DIAGNOSTICO     VARCHAR2(500),
    CIE10_CODIGO    VARCHAR2(10),                   -- Código CIE-10
    TRATAMIENTO     NCLOB,
    NOTAS_MEDICO    NCLOB,
    NOTAS_ENFERMERO VARCHAR2(1000),

    -- Alta / Egreso
    TIPO_ALTA       VARCHAR2(30)
                        CONSTRAINT CHK_EMG_TIPO_ALTA CHECK (
                            TIPO_ALTA IS NULL OR
                            TIPO_ALTA IN ('VOLUNTARIA','MEDICA','FUGA','FALLECIMIENTO','TRANSFERENCIA')
                        ),
    FECHA_ALTA      DATE,
    HORA_ALTA       VARCHAR2(5),                    -- 'HH24:MI'
    DESTINO_ALTA    VARCHAR2(200),                  -- Servicio destino si TRANSFERIDO

    -- Auditoría
    ACTIVO          NUMBER(1)       NOT NULL    DEFAULT 1
                        CONSTRAINT CHK_EMG_ACTIVO CHECK (ACTIVO IN (0,1)),
    CREATED_BY      NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Foreign keys
    CONSTRAINT FK_EMG_HOSPITAL  FOREIGN KEY (HOSPITAL_ID)   REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_EMG_PACIENTE  FOREIGN KEY (PAC_ID)        REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_EMG_MEDICO    FOREIGN KEY (MEDICO_ID)     REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_EMG_ENFERMERO FOREIGN KEY (ENFERMERO_ID)  REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_EMG_CREATED   FOREIGN KEY (CREATED_BY)    REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_EMG_UPDATED   FOREIGN KEY (UPDATED_BY)    REFERENCES SEC_USUARIOS(USR_ID)
)
TABLESPACE PHI_DATA;

-- ============================================================
-- Índices de rendimiento
-- ============================================================
CREATE INDEX IDX_EMG_HOSPITAL    ON EMG_EMERGENCIAS (HOSPITAL_ID)                      TABLESPACE PHI_IDX;
CREATE INDEX IDX_EMG_FECHA       ON EMG_EMERGENCIAS (HOSPITAL_ID, FECHA_INGRESO)        TABLESPACE PHI_IDX;
CREATE INDEX IDX_EMG_PACIENTE    ON EMG_EMERGENCIAS (HOSPITAL_ID, PAC_ID)              TABLESPACE PHI_IDX;
CREATE INDEX IDX_EMG_MEDICO      ON EMG_EMERGENCIAS (HOSPITAL_ID, MEDICO_ID)           TABLESPACE PHI_IDX;
CREATE INDEX IDX_EMG_ESTADO      ON EMG_EMERGENCIAS (HOSPITAL_ID, ESTADO, FECHA_INGRESO) TABLESPACE PHI_IDX;
CREATE INDEX IDX_EMG_TRIAJE      ON EMG_EMERGENCIAS (HOSPITAL_ID, NIVEL_TRIAJE, ESTADO) TABLESPACE PHI_IDX;

-- ============================================================
-- Trigger: actualizar UPDATED_AT automáticamente
-- ============================================================
CREATE OR REPLACE TRIGGER TRG_EMG_EMERGENCIAS_UPD
    BEFORE UPDATE ON EMG_EMERGENCIAS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ============================================================
-- Comentarios de columnas (documentación Oracle)
-- ============================================================
COMMENT ON TABLE  EMG_EMERGENCIAS                      IS 'Registro de atenciones de urgencias y emergencias — PHI';
COMMENT ON COLUMN EMG_EMERGENCIAS.EMG_ID               IS 'PK autoincremental';
COMMENT ON COLUMN EMG_EMERGENCIAS.HOSPITAL_ID          IS 'Columna VPD — aislamiento multitenant';
COMMENT ON COLUMN EMG_EMERGENCIAS.NIVEL_TRIAJE         IS 'Sistema de Triaje Manchester: ROJO/NARANJA/AMARILLO/VERDE/AZUL';
COMMENT ON COLUMN EMG_EMERGENCIAS.CIE10_CODIGO         IS 'Código CIE-10 del diagnóstico principal';
COMMENT ON COLUMN EMG_EMERGENCIAS.ACTIVO               IS '1=activo, 0=soft-deleted (HIPAA)';
