-- ============================================================
-- HealthTech Solutions — DDL: Módulo Encamamiento (M05)
-- Tabla: ENC_ENCAMAMIENTOS  (admisiones hospitalarias)
-- Tablespace PHI_DATA (TDE habilitado en PROD)
-- VPD: HOSPITAL_ID columna de particionamiento
-- Soft-delete: ACTIVO — nunca DELETE físico (HIPAA)
-- ============================================================

CREATE TABLE ENC_ENCAMAMIENTOS (
    ENC_ID          NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                    CONSTRAINT PK_ENC_ENCAMAMIENTOS PRIMARY KEY,
    HOSPITAL_ID     NUMBER          NOT NULL,

    -- Relaciones
    PAC_ID          NUMBER          NOT NULL,
    CAMA_ID         NUMBER          NOT NULL,
    MEDICO_ID       NUMBER          NOT NULL,       -- Médico tratante
    ENFERMERO_ID    NUMBER,                         -- Enfermero asignado

    -- Orígenes (opcional)
    EMG_ID          NUMBER,                         -- Admisión desde Emergencia
    CIT_ID          NUMBER,                         -- Admisión programada desde Cita

    -- Admisión
    FECHA_INGRESO   DATE            NOT NULL,
    HORA_INGRESO    VARCHAR2(5)     NOT NULL,        -- 'HH24:MI'
    MOTIVO_INGRESO  VARCHAR2(500)   NOT NULL,
    DIAGNOSTICO_INGRESO VARCHAR2(500),
    CIE10_INGRESO   VARCHAR2(10),

    -- Estado clínico
    ESTADO          VARCHAR2(30)    NOT NULL    DEFAULT 'INGRESADO'
                        CONSTRAINT CHK_ENC_ESTADO CHECK (
                            ESTADO IN ('INGRESADO','EN_TRATAMIENTO','EGRESADO','TRASLADADO','FALLECIDO')
                        ),

    -- Notas clínicas (PHI)
    NOTAS_INGRESO   NCLOB,
    EVOLUCION       NCLOB,          -- Notas de evolución diaria
    INDICACIONES    NCLOB,          -- Indicaciones médicas activas

    -- Egreso
    TIPO_EGRESO     VARCHAR2(30)
                        CONSTRAINT CHK_ENC_TIPO_EGR CHECK (
                            TIPO_EGRESO IS NULL OR
                            TIPO_EGRESO IN ('ALTA_MEDICA','VOLUNTARIA','TRASLADO',
                                            'FALLECIMIENTO','FUGA')
                        ),
    FECHA_EGRESO    DATE,
    HORA_EGRESO     VARCHAR2(5),
    DIAGNOSTICO_EGRESO  VARCHAR2(500),
    CIE10_EGRESO    VARCHAR2(10),
    DESTINO_EGRESO  VARCHAR2(200),  -- Servicio destino si TRASLADO
    DIAS_ESTANCIA   NUMBER(4),      -- Calculado al egreso

    -- Auditoría
    ACTIVO          NUMBER(1)       DEFAULT 1
                        CONSTRAINT CHK_ENC_ENC_ACT CHECK (ACTIVO IN (0,1)),
    CREATED_BY      NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Foreign keys
    CONSTRAINT FK_ENC_HOSP      FOREIGN KEY (HOSPITAL_ID)  REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_ENC_PAC       FOREIGN KEY (PAC_ID)       REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_ENC_CAMA      FOREIGN KEY (CAMA_ID)      REFERENCES ENC_CAMAS(CAMA_ID),
    CONSTRAINT FK_ENC_MEDICO    FOREIGN KEY (MEDICO_ID)    REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_ENC_ENFERMERO FOREIGN KEY (ENFERMERO_ID) REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_ENC_EMG       FOREIGN KEY (EMG_ID)       REFERENCES EMG_EMERGENCIAS(EMG_ID),
    CONSTRAINT FK_ENC_CIT       FOREIGN KEY (CIT_ID)       REFERENCES CIT_CITAS(CIT_ID),
    CONSTRAINT FK_ENC_CREATED   FOREIGN KEY (CREATED_BY)   REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_ENC_UPDATED   FOREIGN KEY (UPDATED_BY)   REFERENCES SEC_USUARIOS(USR_ID)
)
TABLESPACE PHI_DATA;

-- ============================================================
-- Índices
-- ============================================================
CREATE INDEX IDX_ENC_HOSPITAL   ON ENC_ENCAMAMIENTOS (HOSPITAL_ID)                         TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENC_PACIENTE   ON ENC_ENCAMAMIENTOS (HOSPITAL_ID, PAC_ID)                 TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENC_CAMA_IDX   ON ENC_ENCAMAMIENTOS (HOSPITAL_ID, CAMA_ID, ESTADO)        TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENC_MEDICO     ON ENC_ENCAMAMIENTOS (HOSPITAL_ID, MEDICO_ID, FECHA_INGRESO) TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENC_ESTADO     ON ENC_ENCAMAMIENTOS (HOSPITAL_ID, ESTADO, FECHA_INGRESO)   TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENC_FECHA      ON ENC_ENCAMAMIENTOS (HOSPITAL_ID, FECHA_INGRESO)           TABLESPACE PHI_IDX;

-- ============================================================
-- Trigger UPDATED_AT
-- ============================================================
CREATE OR REPLACE TRIGGER TRG_ENC_ENCAMAMIENTOS_UPD
    BEFORE UPDATE ON ENC_ENCAMAMIENTOS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- ============================================================
-- Comentarios
-- ============================================================
COMMENT ON TABLE  ENC_ENCAMAMIENTOS                  IS 'Admisiones hospitalarias (encamamiento) — PHI';
COMMENT ON COLUMN ENC_ENCAMAMIENTOS.HOSPITAL_ID      IS 'Columna VPD — aislamiento multitenant';
COMMENT ON COLUMN ENC_ENCAMAMIENTOS.ESTADO           IS 'INGRESADO|EN_TRATAMIENTO|EGRESADO|TRASLADADO|FALLECIDO';
COMMENT ON COLUMN ENC_ENCAMAMIENTOS.DIAS_ESTANCIA    IS 'Calculado al registrar egreso: FECHA_EGRESO - FECHA_INGRESO';
COMMENT ON COLUMN ENC_ENCAMAMIENTOS.ACTIVO           IS '1=activo, 0=soft-deleted (HIPAA)';
