-- =======================================================================
-- M06 — Cirugía / Quirófano
-- Tabla: CIR_CIRUGIAS
-- Esquema: HealthTech Solutions SaaS — Oracle 19c / XE
-- HIPAA: PHI_DATA tablespace (TDE en PROD)
-- =======================================================================

-- Drop seguro para re-despliegue
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CIR_CIRUGIAS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CIR_CIRUGIAS (
    -- PK
    CIR_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    -- Multi-tenancy (VPD)
    HOSPITAL_ID         NUMBER          NOT NULL,

    -- Paciente y equipo quirúrgico
    PAC_ID              NUMBER          NOT NULL,
    CIRUJANO_ID         NUMBER          NOT NULL,
    ANESTESIOLOGO_ID    NUMBER,
    ENFERMERO_INST_ID   NUMBER,           -- Instrumentista
    ENFERMERO_CIRC_ID   NUMBER,           -- Circulante

    -- Origen (opcional)
    EMG_ID              NUMBER,           -- Desde emergencia
    ENC_ID              NUMBER,           -- Desde encamamiento

    -- Programación
    FECHA_PROGRAMADA    DATE            NOT NULL,
    HORA_INI_PROG       VARCHAR2(5)     NOT NULL,     -- HH:MI
    HORA_FIN_PROG       VARCHAR2(5),
    DURACION_EST_MIN    NUMBER(5),        -- Duración estimada en minutos

    -- Quirófano y clasificación
    QUIROFANO           VARCHAR2(30)    NOT NULL,
    TIPO_CIRUGIA        VARCHAR2(200)   NOT NULL,
    ESPECIALIDAD        VARCHAR2(100),
    PRIORIDAD           VARCHAR2(20)    DEFAULT 'ELECTIVA'  NOT NULL,
    TIPO_ANESTESIA      VARCHAR2(30)    DEFAULT 'GENERAL'   NOT NULL,

    -- Pre-operatorio
    CIE10_PRE           VARCHAR2(10),
    DIAGNOSTICO_PREOP   VARCHAR2(500),
    NOTAS_PREOP         VARCHAR2(2000),

    -- Estado de la máquina de estados
    ESTADO              VARCHAR2(30)    DEFAULT 'PROGRAMADA' NOT NULL,

    -- Datos intraoperatorios / post-operatorios (se completan al finalizar)
    FECHA_INICIO_REAL   DATE,
    HORA_INICIO_REAL    VARCHAR2(5),
    FECHA_FIN_REAL      DATE,
    HORA_FIN_REAL       VARCHAR2(5),
    DURACION_REAL_MIN   NUMBER(5),        -- Minutos reales

    HALLAZGOS           VARCHAR2(2000),   -- Hallazgos intraoperatorios
    COMPLICACIONES      VARCHAR2(500),
    NOTAS_POSTOP        VARCHAR2(2000),
    DIAGNOSTICO_POSTOP  VARCHAR2(500),
    CIE10_POST          VARCHAR2(10),

    -- Motivo de cancelación / suspensión
    MOTIVO_CANCELACION  VARCHAR2(500),

    -- Auditoría HIPAA
    ACTIVO              NUMBER(1)       DEFAULT 1           NOT NULL,
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          NUMBER,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- =====================================================================
    -- Constraints
    -- =====================================================================
    CONSTRAINT CHK_CIR_PRIORIDAD    CHECK (PRIORIDAD    IN ('EMERGENCIA', 'URGENTE', 'ELECTIVA')),
    CONSTRAINT CHK_CIR_ANESTESIA    CHECK (TIPO_ANESTESIA IN ('GENERAL', 'REGIONAL', 'LOCAL', 'SEDACION', 'NINGUNA')),
    CONSTRAINT CHK_CIR_ESTADO       CHECK (ESTADO IN ('PROGRAMADA', 'EN_CURSO', 'COMPLETADA', 'SUSPENDIDA', 'CANCELADA')),
    CONSTRAINT CHK_CIR_ACTIVO       CHECK (ACTIVO IN (0, 1)),

    -- Foreign Keys
    CONSTRAINT FK_CIR_HOSPITAL      FOREIGN KEY (HOSPITAL_ID)       REFERENCES SEC_HOSPITALES(HOSPITAL_ID),
    CONSTRAINT FK_CIR_PACIENTE      FOREIGN KEY (PAC_ID)            REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_CIR_CIRUJANO      FOREIGN KEY (CIRUJANO_ID)       REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIR_ANEST         FOREIGN KEY (ANESTESIOLOGO_ID)  REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIR_ENF_INST      FOREIGN KEY (ENFERMERO_INST_ID) REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIR_ENF_CIRC      FOREIGN KEY (ENFERMERO_CIRC_ID) REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_CIR_EMERGENCIA    FOREIGN KEY (EMG_ID)            REFERENCES EMG_EMERGENCIAS(EMG_ID),
    CONSTRAINT FK_CIR_ENCAMAMIENTO  FOREIGN KEY (ENC_ID)            REFERENCES ENC_ENCAMAMIENTOS(ENC_ID)

) TABLESPACE PHI_DATA;


-- =====================================================================
-- Índices de rendimiento
-- =====================================================================
CREATE INDEX IDX_CIR_HOSPITAL   ON CIR_CIRUGIAS (HOSPITAL_ID)                          TABLESPACE HT_IDX;
CREATE INDEX IDX_CIR_PACIENTE   ON CIR_CIRUGIAS (PAC_ID)                               TABLESPACE HT_IDX;
CREATE INDEX IDX_CIR_CIRUJANO   ON CIR_CIRUGIAS (CIRUJANO_ID)                          TABLESPACE HT_IDX;
CREATE INDEX IDX_CIR_FECHA      ON CIR_CIRUGIAS (FECHA_PROGRAMADA)                     TABLESPACE HT_IDX;
CREATE INDEX IDX_CIR_ESTADO     ON CIR_CIRUGIAS (ESTADO)                               TABLESPACE HT_IDX;
CREATE INDEX IDX_CIR_PRIORIDAD  ON CIR_CIRUGIAS (PRIORIDAD)                            TABLESPACE HT_IDX;
-- Índice compuesto: agenda de quirófano por día
CREATE INDEX IDX_CIR_AGENDA     ON CIR_CIRUGIAS (HOSPITAL_ID, QUIROFANO, FECHA_PROGRAMADA) TABLESPACE HT_IDX;


-- =====================================================================
-- Trigger: auto-actualización de UPDATED_AT
-- =====================================================================
CREATE OR REPLACE TRIGGER TRG_CIR_CIRUGIAS_UPD
    BEFORE UPDATE ON CIR_CIRUGIAS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- =====================================================================
-- Comentarios descriptivos
-- =====================================================================
COMMENT ON TABLE  CIR_CIRUGIAS IS 'M06 — Programación y registro de intervenciones quirúrgicas. Datos PHI bajo TDE.';
COMMENT ON COLUMN CIR_CIRUGIAS.PRIORIDAD        IS 'EMERGENCIA | URGENTE | ELECTIVA';
COMMENT ON COLUMN CIR_CIRUGIAS.TIPO_ANESTESIA   IS 'GENERAL | REGIONAL | LOCAL | SEDACION | NINGUNA';
COMMENT ON COLUMN CIR_CIRUGIAS.ESTADO           IS 'PROGRAMADA → EN_CURSO → COMPLETADA | SUSPENDIDA | CANCELADA';
COMMENT ON COLUMN CIR_CIRUGIAS.DURACION_EST_MIN IS 'Duración estimada en minutos';
COMMENT ON COLUMN CIR_CIRUGIAS.DURACION_REAL_MIN IS 'Duración real calculada al completar: HORA_FIN_REAL - HORA_INICIO_REAL';
COMMENT ON COLUMN CIR_CIRUGIAS.ACTIVO           IS '1 = activo (soft-delete), 0 = eliminado lógicamente';
COMMENT ON COLUMN CIR_CIRUGIAS.EMG_ID           IS 'FK opcional: cirugía originada desde módulo de emergencias';
COMMENT ON COLUMN CIR_CIRUGIAS.ENC_ID           IS 'FK opcional: cirugía originada desde encamamiento/hospitalización';
