-- =======================================================================
-- M07 — Laboratorio: Órdenes de Exámenes
-- Tabla: LAB_ORDENES
-- Esquema: HealthTech Solutions SaaS — Oracle 19c / XE
-- HIPAA: PHI_DATA tablespace (TDE en PROD)
-- =======================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_ORDENES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LAB_ORDENES (
    -- PK
    LAB_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    -- Multi-tenancy (VPD)
    HOSPITAL_ID         NUMBER          NOT NULL,

    -- Paciente y personal
    PAC_ID              NUMBER          NOT NULL,
    MEDICO_SOLIC_ID     NUMBER          NOT NULL,     -- Médico que solicita
    LABORATORISTA_ID    NUMBER,                       -- Quien procesa la muestra

    -- Origen opcional
    EMG_ID              NUMBER,                       -- Desde emergencia
    ENC_ID              NUMBER,                       -- Desde encamamiento
    CIT_ID              NUMBER,                       -- Desde cita ambulatoria

    -- Datos de solicitud
    FECHA_SOLICITUD      DATE            NOT NULL,
    HORA_SOLICITUD       VARCHAR2(5)     NOT NULL,    -- HH:MI

    -- Clasificación
    PRIORIDAD            VARCHAR2(20)    DEFAULT 'NORMAL'   NOT NULL,
    TIPO_MUESTRA         VARCHAR2(30)    DEFAULT 'SANGRE'   NOT NULL,
    GRUPO_EXAMEN         VARCHAR2(30),                -- Categoría general (HEMATOLOGIA, QUIMICA, etc.)
    EXAMENES_SOLICITADOS VARCHAR2(2000)  NOT NULL,    -- Lista descriptiva de exámenes
    OBSERVACIONES_CLIN   VARCHAR2(500),               -- Contexto clínico para el laboratorio

    -- Estado (máquina de estados)
    ESTADO               VARCHAR2(30)    DEFAULT 'PENDIENTE' NOT NULL,

    -- Toma de muestra (llenado al procesar)
    FECHA_MUESTRA        DATE,
    HORA_MUESTRA         VARCHAR2(5),

    -- Entrega de resultados (llenado al completar)
    FECHA_RESULTADO      DATE,
    HORA_RESULTADO       VARCHAR2(5),

    -- Notas y cancelación
    NOTAS_LABORATORIO    VARCHAR2(1000),
    MOTIVO_CANCELACION   VARCHAR2(500),

    -- Auditoría HIPAA
    ACTIVO               NUMBER(1)       DEFAULT 1           NOT NULL,
    CREATED_BY           NUMBER,
    CREATED_AT           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY           NUMBER,
    UPDATED_AT           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- =====================================================================
    -- Constraints
    -- =====================================================================
    CONSTRAINT CHK_LAB_PRIORIDAD CHECK (PRIORIDAD    IN ('NORMAL', 'URGENTE', 'EMERGENCIA')),
    CONSTRAINT CHK_LAB_MUESTRA   CHECK (TIPO_MUESTRA IN ('SANGRE', 'ORINA', 'HECES', 'ESPUTO',
                                                          'LCR', 'TEJIDO', 'HISOPADO', 'OTRO')),
    CONSTRAINT CHK_LAB_ESTADO    CHECK (ESTADO IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA')),
    CONSTRAINT CHK_LAB_ACTIVO    CHECK (ACTIVO IN (0, 1)),

    -- Foreign Keys
    CONSTRAINT FK_LAB_HOSPITAL      FOREIGN KEY (HOSPITAL_ID)     REFERENCES SEC_HOSPITALES(HOSPITAL_ID),
    CONSTRAINT FK_LAB_PACIENTE      FOREIGN KEY (PAC_ID)          REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_LAB_MEDICO        FOREIGN KEY (MEDICO_SOLIC_ID) REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_LAB_LABORATORISTA FOREIGN KEY (LABORATORISTA_ID) REFERENCES SEC_USUARIOS(USR_ID),
    CONSTRAINT FK_LAB_EMERGENCIA    FOREIGN KEY (EMG_ID)          REFERENCES EMG_EMERGENCIAS(EMG_ID),
    CONSTRAINT FK_LAB_ENCAMAMIENTO  FOREIGN KEY (ENC_ID)          REFERENCES ENC_ENCAMAMIENTOS(ENC_ID),
    CONSTRAINT FK_LAB_CITA          FOREIGN KEY (CIT_ID)          REFERENCES CIT_CITAS(CIT_ID)

) TABLESPACE PHI_DATA;


-- =====================================================================
-- Índices de rendimiento
-- =====================================================================
CREATE INDEX IDX_LAB_HOSPITAL  ON LAB_ORDENES (HOSPITAL_ID)       TABLESPACE HT_IDX;
CREATE INDEX IDX_LAB_PACIENTE  ON LAB_ORDENES (PAC_ID)            TABLESPACE HT_IDX;
CREATE INDEX IDX_LAB_MEDICO    ON LAB_ORDENES (MEDICO_SOLIC_ID)   TABLESPACE HT_IDX;
CREATE INDEX IDX_LAB_FECHA     ON LAB_ORDENES (FECHA_SOLICITUD)   TABLESPACE HT_IDX;
CREATE INDEX IDX_LAB_ESTADO    ON LAB_ORDENES (ESTADO)            TABLESPACE HT_IDX;
CREATE INDEX IDX_LAB_PRIORIDAD ON LAB_ORDENES (PRIORIDAD)         TABLESPACE HT_IDX;


-- =====================================================================
-- Trigger: auto-actualización de UPDATED_AT
-- =====================================================================
CREATE OR REPLACE TRIGGER TRG_LAB_ORDENES_UPD
    BEFORE UPDATE ON LAB_ORDENES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- =====================================================================
-- Comentarios
-- =====================================================================
COMMENT ON TABLE  LAB_ORDENES IS 'M07 — Órdenes de exámenes de laboratorio. PHI bajo TDE en PROD.';
COMMENT ON COLUMN LAB_ORDENES.PRIORIDAD            IS 'NORMAL | URGENTE | EMERGENCIA';
COMMENT ON COLUMN LAB_ORDENES.TIPO_MUESTRA         IS 'SANGRE | ORINA | HECES | ESPUTO | LCR | TEJIDO | HISOPADO | OTRO';
COMMENT ON COLUMN LAB_ORDENES.ESTADO               IS 'PENDIENTE → EN_PROCESO → COMPLETADA | CANCELADA';
COMMENT ON COLUMN LAB_ORDENES.EXAMENES_SOLICITADOS IS 'Lista descriptiva de exámenes solicitados (texto libre)';
COMMENT ON COLUMN LAB_ORDENES.ACTIVO               IS '1 = activo (soft-delete), 0 = eliminado lógicamente';
