-- =======================================================================
-- M07 — Laboratorio: Resultados Individuales por Examen
-- Tabla: LAB_RESULTADOS
-- Esquema: HealthTech Solutions SaaS — Oracle 19c / XE
-- HIPAA: PHI_DATA tablespace (TDE en PROD)
-- =======================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_RESULTADOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LAB_RESULTADOS (
    -- PK
    RES_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    -- Relación con la orden
    LAB_ID              NUMBER          NOT NULL,
    HOSPITAL_ID         NUMBER          NOT NULL,

    -- Resultado del examen
    NOMBRE_EXAMEN       VARCHAR2(200)   NOT NULL,    -- Nombre del examen (ej: "Hemoglobina")
    VALOR               VARCHAR2(500)   NOT NULL,    -- Valor obtenido (numérico o texto)
    UNIDAD              VARCHAR2(50),                -- Unidad de medida (ej: "g/dL", "mmol/L")

    -- Rangos de referencia
    RANGO_MIN           VARCHAR2(100),               -- Límite inferior de referencia
    RANGO_MAX           VARCHAR2(100),               -- Límite superior de referencia
    VALOR_REFERENCIA    VARCHAR2(200),               -- Descripción alternativa del rango

    -- Interpretación
    INTERPRETACION      VARCHAR2(500),               -- Notas de interpretación clínica
    ESTADO_RESULTADO    VARCHAR2(20)    DEFAULT 'NORMAL' NOT NULL,  -- Clasificación del resultado

    -- Auditoría
    ACTIVO              NUMBER(1)       DEFAULT 1           NOT NULL,
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- =====================================================================
    -- Constraints
    -- =====================================================================
    CONSTRAINT CHK_RES_ESTADO CHECK (ESTADO_RESULTADO IN ('NORMAL', 'ALTO', 'BAJO', 'CRITICO', 'PENDIENTE')),
    CONSTRAINT CHK_RES_ACTIVO CHECK (ACTIVO IN (0, 1)),

    -- Foreign Keys
    CONSTRAINT FK_RES_ORDEN    FOREIGN KEY (LAB_ID)      REFERENCES LAB_ORDENES(LAB_ID),
    CONSTRAINT FK_RES_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES SEC_HOSPITALES(HOSPITAL_ID)

) TABLESPACE PHI_DATA;


-- =====================================================================
-- Índices
-- =====================================================================
CREATE INDEX IDX_RES_ORDEN    ON LAB_RESULTADOS (LAB_ID)           TABLESPACE HT_IDX;
CREATE INDEX IDX_RES_HOSPITAL ON LAB_RESULTADOS (HOSPITAL_ID)      TABLESPACE HT_IDX;
CREATE INDEX IDX_RES_ESTADO   ON LAB_RESULTADOS (ESTADO_RESULTADO)  TABLESPACE HT_IDX;


-- =====================================================================
-- Trigger: auto-actualización de UPDATED_AT
-- =====================================================================
CREATE OR REPLACE TRIGGER TRG_LAB_RESULTADOS_UPD
    BEFORE UPDATE ON LAB_RESULTADOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- =====================================================================
-- Comentarios
-- =====================================================================
COMMENT ON TABLE  LAB_RESULTADOS IS 'M07 — Resultados individuales de exámenes por orden de laboratorio. PHI.';
COMMENT ON COLUMN LAB_RESULTADOS.ESTADO_RESULTADO IS 'NORMAL | ALTO | BAJO | CRITICO | PENDIENTE';
COMMENT ON COLUMN LAB_RESULTADOS.VALOR            IS 'Resultado del examen — puede ser numérico o texto (ej: Positivo/Negativo)';
COMMENT ON COLUMN LAB_RESULTADOS.RANGO_MIN        IS 'Valor mínimo del rango de referencia para la población';
COMMENT ON COLUMN LAB_RESULTADOS.RANGO_MAX        IS 'Valor máximo del rango de referencia para la población';
