-- ============================================================
-- HealthTech Solutions — DDL: BOD_PRODUCTOS (M09)
-- Catálogo de productos/insumos del almacén hospitalario
-- HIPAA: datos en tablespace PHI_DATA (TDE en PROD)
-- VPD:   HOSPITAL_ID presente para filtrado automático
-- Nota:  Excluye medicamentos (esos van en FAR_MEDICAMENTOS)
-- ============================================================

CREATE TABLE BOD_PRODUCTOS (
    PRO_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                        CONSTRAINT PK_BOD_PRO PRIMARY KEY,
    HOSPITAL_ID         NUMBER(10)      NOT NULL,

    -- Identificación del producto
    CODIGO              VARCHAR2(50)    DEFAULT '',
    NOMBRE              VARCHAR2(200)   NOT NULL,
    DESCRIPCION         VARCHAR2(500)   DEFAULT '',

    -- Clasificación
    CATEGORIA           VARCHAR2(30)    DEFAULT 'MATERIAL_MEDICO'
                        CONSTRAINT CK_BOD_PRO_CAT CHECK (
                            CATEGORIA IN ('MATERIAL_MEDICO','INSUMO_QUIRURGICO','LIMPIEZA',
                                          'OFICINA','EQUIPO','ALIMENTACION','OTRO')
                        ),
    UNIDAD_MEDIDA       VARCHAR2(30)    DEFAULT 'unidad',

    -- Inventario
    STOCK_ACTUAL        NUMBER(12,3)    DEFAULT 0 NOT NULL,
    STOCK_MINIMO        NUMBER(12,3)    DEFAULT 0 NOT NULL,
    STOCK_MAXIMO        NUMBER(12,3),                         -- NULL = sin límite superior
    PRECIO_UNITARIO     NUMBER(12,4)    DEFAULT 0,

    -- Proveedor y ubicación
    PROVEEDOR           VARCHAR2(200)   DEFAULT '',
    UBICACION           VARCHAR2(100)   DEFAULT '',

    -- Control
    ACTIVO              NUMBER(1)       DEFAULT 1
                        CONSTRAINT CK_BOD_PRO_ACTIVO CHECK (ACTIVO IN (0,1)),

    -- Auditoría HIPAA
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          NUMBER,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Foreign Keys
    CONSTRAINT FK_BOD_PRO_HOSPITAL  FOREIGN KEY (HOSPITAL_ID) REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_BOD_PRO_CREATEDBY FOREIGN KEY (CREATED_BY)  REFERENCES SEC_USUARIOS(USU_ID),
    CONSTRAINT FK_BOD_PRO_UPDATEDBY FOREIGN KEY (UPDATED_BY)  REFERENCES SEC_USUARIOS(USU_ID)
) TABLESPACE PHI_DATA;

-- Índices
CREATE INDEX IDX_BOD_PRO_HOSPITAL  ON BOD_PRODUCTOS (HOSPITAL_ID)                    TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_PRO_NOMBRE    ON BOD_PRODUCTOS (HOSPITAL_ID, NOMBRE)            TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_PRO_CATEGORIA ON BOD_PRODUCTOS (HOSPITAL_ID, CATEGORIA)         TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_PRO_STOCK     ON BOD_PRODUCTOS (HOSPITAL_ID, STOCK_ACTUAL)      TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_PRO_CODIGO    ON BOD_PRODUCTOS (HOSPITAL_ID, CODIGO)            TABLESPACE PHI_IDX;

-- Trigger auditoría UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_BOD_PRO_UPD
    BEFORE UPDATE ON BOD_PRODUCTOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

COMMIT;
