-- ============================================================
-- HealthTech Solutions — DDL: BOD_MOVIMIENTOS (M09)
-- Registro inmutable de movimientos de inventario de bodega
-- HIPAA: datos en tablespace PHI_DATA (TDE en PROD)
-- VPD:   HOSPITAL_ID presente para filtrado automático
-- Inmutabilidad: sin UPDATE/DELETE — trazabilidad de stock
-- ============================================================

CREATE TABLE BOD_MOVIMIENTOS (
    MOV_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                        CONSTRAINT PK_BOD_MOV PRIMARY KEY,
    HOSPITAL_ID         NUMBER(10)      NOT NULL,

    -- Producto afectado
    PRO_ID              NUMBER          NOT NULL,

    -- Tipo de movimiento (máquina de estados de stock)
    TIPO_MOVIMIENTO     VARCHAR2(20)    NOT NULL
                        CONSTRAINT CK_BOD_MOV_TIPO CHECK (
                            TIPO_MOVIMIENTO IN ('ENTRADA','SALIDA','AJUSTE_POSITIVO',
                                               'AJUSTE_NEGATIVO','BAJA')
                        ),

    -- Cantidades (trazabilidad completa del stock)
    CANTIDAD            NUMBER(12,3)    NOT NULL,
    CANTIDAD_ANTERIOR   NUMBER(12,3)    NOT NULL,
    CANTIDAD_POSTERIOR  NUMBER(12,3)    NOT NULL,

    -- Trazabilidad adicional
    MOTIVO              VARCHAR2(500)   DEFAULT '',
    REFERENCIA          VARCHAR2(200)   DEFAULT '',     -- Nro. orden, factura, etc.
    DEPARTAMENTO        VARCHAR2(100)   DEFAULT '',     -- Servicio que solicitó
    PROVEEDOR           VARCHAR2(200)   DEFAULT '',     -- Solo aplica en ENTRADA

    -- Auditoría (append-only: no hay UPDATED_BY / UPDATED_AT)
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Foreign Keys
    CONSTRAINT FK_BOD_MOV_HOSPITAL  FOREIGN KEY (HOSPITAL_ID) REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_BOD_MOV_PRODUCTO  FOREIGN KEY (PRO_ID)      REFERENCES BOD_PRODUCTOS(PRO_ID),
    CONSTRAINT FK_BOD_MOV_CREATEDBY FOREIGN KEY (CREATED_BY)  REFERENCES SEC_USUARIOS(USU_ID)
) TABLESPACE PHI_DATA;

-- Índices
CREATE INDEX IDX_BOD_MOV_HOSPITAL  ON BOD_MOVIMIENTOS (HOSPITAL_ID)                       TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_MOV_PRODUCTO  ON BOD_MOVIMIENTOS (HOSPITAL_ID, PRO_ID)               TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_MOV_TIPO      ON BOD_MOVIMIENTOS (HOSPITAL_ID, TIPO_MOVIMIENTO)      TABLESPACE PHI_IDX;
CREATE INDEX IDX_BOD_MOV_FECHA     ON BOD_MOVIMIENTOS (HOSPITAL_ID, CREATED_AT)           TABLESPACE PHI_IDX;

-- Sin trigger de UPDATED_AT (registro inmutable)

COMMIT;
