-- ============================================================
-- HealthTech Solutions — DDL: ENF_SIGNOS_VITALES (M10)
-- Registro de signos vitales tomados por enfermería
-- HIPAA: PHI — datos en tablespace PHI_DATA (TDE en PROD)
-- VPD:   HOSPITAL_ID presente para filtrado automático
-- Inmutabilidad (append-only): sin UPDATE/DELETE — auditoría clínica
-- ============================================================

CREATE TABLE ENF_SIGNOS_VITALES (
    SIG_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                        CONSTRAINT PK_ENF_SIG PRIMARY KEY,
    HOSPITAL_ID         NUMBER(10)      NOT NULL,

    -- Relaciones
    PAC_ID              NUMBER          NOT NULL,
    ENC_ID              NUMBER,                         -- FK opcional: encamamiento activo

    -- Signos vitales (todos opcionales excepto que al menos 1 debe estar presente)
    TEMPERATURA         NUMBER(4,1),                    -- °C
    PRESION_SISTOLICA   NUMBER(5),                      -- mmHg
    PRESION_DIASTOLICA  NUMBER(5),                      -- mmHg
    FRECUENCIA_CARDIACA NUMBER(5),                      -- bpm
    FRECUENCIA_RESP     NUMBER(5),                      -- rpm
    SATURACION_O2       NUMBER(5,2),                    -- %
    GLUCEMIA            NUMBER(6,1),                    -- mg/dL
    PESO                NUMBER(5,2),                    -- kg
    TALLA               NUMBER(5,2),                    -- cm
    GLASGOW             NUMBER(2),                      -- 3-15 (Escala de coma de Glasgow)
    OBSERVACIONES       VARCHAR2(500)   DEFAULT '',

    -- Auditoría (append-only: no hay UPDATED_BY / UPDATED_AT)
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Constraints de rango clínico
    CONSTRAINT CK_ENF_SIG_TEMP      CHECK (TEMPERATURA       BETWEEN 30 AND 45),
    CONSTRAINT CK_ENF_SIG_PSIST     CHECK (PRESION_SISTOLICA BETWEEN 50 AND 300),
    CONSTRAINT CK_ENF_SIG_PDIAS     CHECK (PRESION_DIASTOLICA BETWEEN 20 AND 200),
    CONSTRAINT CK_ENF_SIG_FC        CHECK (FRECUENCIA_CARDIACA BETWEEN 20 AND 300),
    CONSTRAINT CK_ENF_SIG_FR        CHECK (FRECUENCIA_RESP    BETWEEN 5  AND 60),
    CONSTRAINT CK_ENF_SIG_SAT       CHECK (SATURACION_O2      BETWEEN 0  AND 100),
    CONSTRAINT CK_ENF_SIG_GLASGOW   CHECK (GLASGOW            BETWEEN 3  AND 15),

    -- Foreign Keys
    CONSTRAINT FK_ENF_SIG_HOSPITAL  FOREIGN KEY (HOSPITAL_ID) REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_ENF_SIG_PACIENTE  FOREIGN KEY (PAC_ID)      REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_ENF_SIG_ENC       FOREIGN KEY (ENC_ID)      REFERENCES ENC_ENCAMAMIENTOS(ENC_ID),
    CONSTRAINT FK_ENF_SIG_CREATEDBY FOREIGN KEY (CREATED_BY)  REFERENCES SEC_USUARIOS(USU_ID)
) TABLESPACE PHI_DATA;

-- Índices
CREATE INDEX IDX_ENF_SIG_HOSPITAL  ON ENF_SIGNOS_VITALES (HOSPITAL_ID)                    TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_SIG_PACIENTE  ON ENF_SIGNOS_VITALES (HOSPITAL_ID, PAC_ID, CREATED_AT) TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_SIG_ENC       ON ENF_SIGNOS_VITALES (HOSPITAL_ID, ENC_ID)            TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_SIG_FECHA     ON ENF_SIGNOS_VITALES (HOSPITAL_ID, CREATED_AT)        TABLESPACE PHI_IDX;

-- Sin trigger de UPDATED_AT (registro append-only)

COMMIT;
