-- ============================================================
-- HealthTech Solutions — DDL: ENF_NOTAS (M10)
-- Notas clínicas registradas por enfermería
-- HIPAA: PHI — datos en tablespace PHI_DATA (TDE en PROD)
-- VPD:   HOSPITAL_ID presente para filtrado automático
-- Inmutabilidad (append-only): sin UPDATE/DELETE — auditoría clínica
-- ============================================================

CREATE TABLE ENF_NOTAS (
    NOTA_ID             NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                        CONSTRAINT PK_ENF_NOTA PRIMARY KEY,
    HOSPITAL_ID         NUMBER(10)      NOT NULL,

    -- Relaciones
    PAC_ID              NUMBER          NOT NULL,
    ENC_ID              NUMBER,                         -- FK opcional: encamamiento activo

    -- Contenido de la nota
    TIPO_NOTA           VARCHAR2(30)    DEFAULT 'EVOLUCION'
                        CONSTRAINT CK_ENF_NOTA_TIPO CHECK (
                            TIPO_NOTA IN ('EVOLUCION','PROCEDIMIENTO','MEDICAMENTO',
                                          'INCIDENTE','INGRESO','EGRESO','OTRO')
                        ),
    CONTENIDO           CLOB            NOT NULL,       -- Texto libre de la nota clínica
    ES_URGENTE          NUMBER(1)       DEFAULT 0
                        CONSTRAINT CK_ENF_NOTA_URG CHECK (ES_URGENTE IN (0,1)),

    -- Auditoría (append-only: no hay UPDATED_BY / UPDATED_AT)
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Foreign Keys
    CONSTRAINT FK_ENF_NOTA_HOSPITAL  FOREIGN KEY (HOSPITAL_ID) REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_ENF_NOTA_PACIENTE  FOREIGN KEY (PAC_ID)      REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_ENF_NOTA_ENC       FOREIGN KEY (ENC_ID)      REFERENCES ENC_ENCAMAMIENTOS(ENC_ID),
    CONSTRAINT FK_ENF_NOTA_CREATEDBY FOREIGN KEY (CREATED_BY)  REFERENCES SEC_USUARIOS(USU_ID)
) TABLESPACE PHI_DATA;

-- Índices
CREATE INDEX IDX_ENF_NOTA_HOSPITAL ON ENF_NOTAS (HOSPITAL_ID)                           TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_NOTA_PACIENTE ON ENF_NOTAS (HOSPITAL_ID, PAC_ID, CREATED_AT)       TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_NOTA_ENC      ON ENF_NOTAS (HOSPITAL_ID, ENC_ID)                   TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_NOTA_TIPO     ON ENF_NOTAS (HOSPITAL_ID, TIPO_NOTA)                TABLESPACE PHI_IDX;
CREATE INDEX IDX_ENF_NOTA_URGENTE  ON ENF_NOTAS (HOSPITAL_ID, ES_URGENTE, CREATED_AT)   TABLESPACE PHI_IDX;

-- Sin trigger de UPDATED_AT (registro append-only)

COMMIT;
