-- ============================================================
-- HealthTech Solutions — DDL: IMG_ESTUDIOS (PACS Module)
-- Picture Archiving and Communication System — Gestión de imágenes médicas
-- HIPAA: PHI — datos en tablespace PHI_DATA (TDE en PROD)
-- VPD:   HOSPITAL_ID presente para filtrado automático
-- AWS S3: imágenes DICOM almacenadas en S3; solo metadatos en Oracle
-- ============================================================

CREATE TABLE IMG_ESTUDIOS (
    EST_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                        CONSTRAINT PK_IMG_EST PRIMARY KEY,
    HOSPITAL_ID         NUMBER(10)      NOT NULL,

    -- Relaciones principales
    PAC_ID              NUMBER          NOT NULL,
    MEDICO_SOL_ID       NUMBER          NOT NULL,      -- Médico solicitante
    TECNICO_ID          NUMBER,                         -- Técnico radiólogo
    RADIOLOGO_ID        NUMBER,                         -- Radiólogo que informa

    -- Origen opcional (trazabilidad entre módulos)
    ENC_ID              NUMBER,                         -- Desde encamamiento
    EMG_ID              NUMBER,                         -- Desde emergencia
    CIT_ID              NUMBER,                         -- Desde cita ambulatoria

    -- Clasificación del estudio
    MODALIDAD           VARCHAR2(30)    NOT NULL
                        CONSTRAINT CK_IMG_EST_MOD CHECK (
                            MODALIDAD IN ('XRAY','CT','MRI','ULTRASONIDO','MAMMOGRAFIA',
                                          'PET','ANGIOGRAFIA','FLUOROSCOPIA','DENSITOMETRIA','OTRO')
                        ),
    REGION_ANATOMICA    VARCHAR2(30)    DEFAULT 'OTRO'
                        CONSTRAINT CK_IMG_EST_REG CHECK (
                            REGION_ANATOMICA IN ('CRANEO','TORAX','ABDOMEN','COLUMNA',
                                                  'EXTREMIDADES','PELVIS','CORAZON','CUELLO',
                                                  'MAMA','CUERPO_ENTERO','OTRO')
                        ),
    DESCRIPCION_CLINICA VARCHAR2(500)   NOT NULL,
    PRIORIDAD           VARCHAR2(20)    DEFAULT 'NORMAL'
                        CONSTRAINT CK_IMG_EST_PRI CHECK (
                            PRIORIDAD IN ('NORMAL','URGENTE','EMERGENCIA')
                        ),

    -- Estado del flujo
    ESTADO              VARCHAR2(20)    DEFAULT 'SOLICITADO'
                        CONSTRAINT CK_IMG_EST_EST CHECK (
                            ESTADO IN ('SOLICITADO','EN_PROCESO','COMPLETADO','CANCELADO')
                        ),

    -- Fechas del flujo
    FECHA_SOLICITUD     DATE            NOT NULL,
    FECHA_REALIZACION   DATE,
    FECHA_INFORME       DATE,

    -- Almacenamiento AWS S3 (metadatos de localización de imágenes)
    S3_BUCKET           VARCHAR2(100)   DEFAULT '',    -- Ej: 'healthtech-pacs-prod'
    S3_PREFIX           VARCHAR2(500)   DEFAULT '',    -- Ej: 'hosp-01/2026/03/EST-00123/'
    NUM_IMAGENES        NUMBER(5)       DEFAULT 0,     -- Contador de imágenes subidas

    -- Informe radiológico
    INFORME             NCLOB,                          -- Texto del informe (HIPAA: cifrado TDE)
    MOTIVO_CANCELACION  VARCHAR2(500)   DEFAULT '',

    -- Auditoría HIPAA
    ACTIVO              NUMBER(1)       DEFAULT 1
                        CONSTRAINT CK_IMG_EST_ACT CHECK (ACTIVO IN (0,1)),
    CREATED_BY          NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          NUMBER,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Foreign Keys
    CONSTRAINT FK_IMG_EST_HOSPITAL   FOREIGN KEY (HOSPITAL_ID)    REFERENCES SEC_HOSPITALES(HOSP_ID),
    CONSTRAINT FK_IMG_EST_PACIENTE   FOREIGN KEY (PAC_ID)         REFERENCES PAC_PACIENTES(PAC_ID),
    CONSTRAINT FK_IMG_EST_MED_SOL    FOREIGN KEY (MEDICO_SOL_ID)  REFERENCES SEC_USUARIOS(USU_ID),
    CONSTRAINT FK_IMG_EST_TECNICO    FOREIGN KEY (TECNICO_ID)     REFERENCES SEC_USUARIOS(USU_ID),
    CONSTRAINT FK_IMG_EST_RADIOLOGO  FOREIGN KEY (RADIOLOGO_ID)   REFERENCES SEC_USUARIOS(USU_ID),
    CONSTRAINT FK_IMG_EST_ENC        FOREIGN KEY (ENC_ID)         REFERENCES ENC_ENCAMAMIENTOS(ENC_ID),
    CONSTRAINT FK_IMG_EST_EMG        FOREIGN KEY (EMG_ID)         REFERENCES EMG_EMERGENCIAS(EMG_ID),
    CONSTRAINT FK_IMG_EST_CIT        FOREIGN KEY (CIT_ID)         REFERENCES CIT_CITAS(CIT_ID),
    CONSTRAINT FK_IMG_EST_CREATEDBY  FOREIGN KEY (CREATED_BY)     REFERENCES SEC_USUARIOS(USU_ID),
    CONSTRAINT FK_IMG_EST_UPDATEDBY  FOREIGN KEY (UPDATED_BY)     REFERENCES SEC_USUARIOS(USU_ID)
) TABLESPACE PHI_DATA;

-- Índices
CREATE INDEX IDX_IMG_EST_HOSPITAL  ON IMG_ESTUDIOS (HOSPITAL_ID)                         TABLESPACE PHI_IDX;
CREATE INDEX IDX_IMG_EST_PACIENTE  ON IMG_ESTUDIOS (HOSPITAL_ID, PAC_ID)                 TABLESPACE PHI_IDX;
CREATE INDEX IDX_IMG_EST_ESTADO    ON IMG_ESTUDIOS (HOSPITAL_ID, ESTADO, FECHA_SOLICITUD) TABLESPACE PHI_IDX;
CREATE INDEX IDX_IMG_EST_MODALIDAD ON IMG_ESTUDIOS (HOSPITAL_ID, MODALIDAD)              TABLESPACE PHI_IDX;
CREATE INDEX IDX_IMG_EST_FECHA     ON IMG_ESTUDIOS (HOSPITAL_ID, FECHA_SOLICITUD)        TABLESPACE PHI_IDX;

-- Trigger auditoría UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_IMG_EST_UPD
    BEFORE UPDATE ON IMG_ESTUDIOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

COMMENT ON TABLE  IMG_ESTUDIOS IS 'PACS — Estudios de imagen médica. Imágenes DICOM en AWS S3.';
COMMENT ON COLUMN IMG_ESTUDIOS.S3_BUCKET IS 'Bucket S3 donde residen las imágenes DICOM del estudio';
COMMENT ON COLUMN IMG_ESTUDIOS.S3_PREFIX IS 'Prefijo de clave S3 (ruta) para las imágenes de este estudio';
COMMENT ON COLUMN IMG_ESTUDIOS.INFORME   IS 'Informe radiológico — PHI cifrado en PROD con TDE';

COMMIT;
