# Generated by Django 5.2.4 on 2026-03-05 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(db_column='HOSPITAL_ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=20, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=150)),
                ('nombre_corto', models.CharField(db_column='NOMBRE_CORTO', max_length=50)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', default='', max_length=300)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', default='', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', default='', max_length=100)),
                ('nit', models.CharField(blank=True, db_column='NIT', default='', max_length=20, unique=True)),
                ('logo_s3_key', models.CharField(blank=True, db_column='LOGO_S3_KEY', default='', max_length=500)),
                ('timezone', models.CharField(db_column='TIMEZONE', default='America/Guatemala', max_length=50)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'db_table': 'SEC_HOSPITALES',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('permiso_id', models.AutoField(db_column='PERMISO_ID', primary_key=True, serialize=False)),
                ('modulo', models.CharField(db_column='MODULO', max_length=50)),
                ('accion', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('approve', 'Aprobar'), ('dispense', 'Dispensar'), ('audit', 'Auditar')], db_column='ACCION', max_length=30)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'SEC_PERMISOS',
                'ordering': ['modulo', 'accion'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(db_column='ROL_ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=50, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', default='', max_length=500)),
                ('nivel', models.SmallIntegerField(choices=[(1, 'Super Admin'), (2, 'Admin Hospital'), (3, 'Personal Clínico'), (4, 'Personal de Apoyo'), (5, 'Externo')], db_column='NIVEL')),
                ('es_sistema', models.BooleanField(db_column='ES_SISTEMA', default=False)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'SEC_ROLES',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usr_id', models.AutoField(db_column='USR_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=50, unique=True)),
                ('primer_nombre', models.CharField(db_column='PRIMER_NOMBRE', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, db_column='SEGUNDO_NOMBRE', default='', max_length=100)),
                ('primer_apellido', models.CharField(db_column='PRIMER_APELLIDO', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, db_column='SEGUNDO_APELLIDO', default='', max_length=100)),
                ('email', models.EmailField(db_column='EMAIL', max_length=150)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', default='', max_length=20)),
                ('tipo_personal', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero/a'), ('FARMACEUTICO', 'Farmacéutico'), ('LABORATORISTA', 'Laboratorista'), ('ADMINISTRATIVO', 'Administrativo'), ('BODEGUERO', 'Bodeguero'), ('AUDITOR', 'Auditor'), ('PROVEEDOR', 'Proveedor'), ('PACIENTE', 'Paciente'), ('OTRO', 'Otro')], db_column='TIPO_PERSONAL', max_length=30)),
                ('especialidad', models.CharField(blank=True, db_column='ESPECIALIDAD', default='', max_length=100)),
                ('no_colegiado', models.CharField(blank=True, db_column='NO_COLEGIADO', default='', max_length=30)),
                ('foto_s3_key', models.CharField(blank=True, db_column='FOTO_S3_KEY', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('cuenta_bloqueada', models.BooleanField(db_column='CUENTA_BLOQUEADA', default=False)),
                ('intentos_fallidos', models.SmallIntegerField(db_column='INTENTOS_FALLIDOS', default=0)),
                ('debe_cambiar_pass', models.BooleanField(db_column='DEBE_CAMBIAR_PASS', default=False)),
                ('ultimo_login', models.DateTimeField(blank=True, db_column='ULTIMO_LOGIN', null=True)),
                ('pass_cambiado_en', models.DateTimeField(db_column='PASS_CAMBIADO_EN', default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_staff', models.BooleanField(db_column='IS_STAFF', default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('hospital', models.ForeignKey(db_column='HOSPITAL_ID', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='security.hospital')),
                ('rol', models.ForeignKey(db_column='ROL_ID', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='security.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'SEC_USUARIOS',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('auditoria_id', models.AutoField(db_column='AUDITORIA_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(blank=True, db_column='HOSPITAL_ID', null=True)),
                ('username_intento', models.CharField(blank=True, db_column='USERNAME_INTENTO', default='', max_length=50)),
                ('tipo_evento', models.CharField(choices=[('LOGIN_OK', 'Login exitoso'), ('LOGIN_FAIL', 'Login fallido'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Refresh de token'), ('TOKEN_REVOKED', 'Token revocado'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('PHI_ACCESS', 'Acceso a PHI'), ('PHI_MODIFY', 'Modificación de PHI'), ('PHI_DELETE', 'Eliminación lógica de PHI'), ('EXPORT', 'Exportación de datos'), ('ADMIN_ACTION', 'Acción administrativa')], db_column='TIPO_EVENTO', max_length=50)),
                ('modulo', models.CharField(blank=True, db_column='MODULO', default='', max_length=50)),
                ('accion', models.CharField(blank=True, db_column='ACCION', default='', max_length=50)),
                ('tabla_afectada', models.CharField(blank=True, db_column='TABLA_AFECTADA', default='', max_length=100)),
                ('registro_id', models.CharField(blank=True, db_column='REGISTRO_ID', default='', max_length=50)),
                ('ip_origen', models.GenericIPAddressField(db_column='IP_ORIGEN')),
                ('user_agent', models.CharField(blank=True, db_column='USER_AGENT', default='', max_length=500)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', default='', max_length=1000)),
                ('exitoso', models.BooleanField(db_column='EXITOSO', default=True)),
                ('mensaje_error', models.CharField(blank=True, db_column='MENSAJE_ERROR', default='', max_length=500)),
                ('duracion_ms', models.IntegerField(blank=True, db_column='DURACION_MS', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('usuario', models.ForeignKey(blank=True, db_column='USR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso',
                'verbose_name_plural': 'Auditorías de Acceso',
                'db_table': 'SEC_AUDITORIA_ACCESOS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('sesion_id', models.AutoField(db_column='SESION_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('refresh_token_jti', models.CharField(db_column='REFRESH_TOKEN_JTI', max_length=100, unique=True)),
                ('ip_origen', models.GenericIPAddressField(db_column='IP_ORIGEN')),
                ('user_agent', models.CharField(blank=True, db_column='USER_AGENT', default='', max_length=500)),
                ('dispositivo', models.CharField(blank=True, db_column='DISPOSITIVO', default='', max_length=100)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_column='CREADA_EN')),
                ('expira_en', models.DateTimeField(db_column='EXPIRA_EN')),
                ('revocada', models.BooleanField(db_column='REVOCADA', default=False)),
                ('revocada_en', models.DateTimeField(blank=True, db_column='REVOCADA_EN', null=True)),
                ('motivo_revocacion', models.CharField(blank=True, db_column='MOTIVO_REVOCACION', default='', max_length=100)),
                ('usuario', models.ForeignKey(db_column='USR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'SEC_SESIONES',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('permiso', models.ForeignKey(db_column='PERMISO_ID', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='security.permiso')),
                ('rol', models.ForeignKey(db_column='ROL_ID', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='security.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'db_table': 'SEC_ROLES_PERMISOS',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
