# Generated by Django 5.2.4 on 2026-03-05 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pac_id', models.AutoField(db_column='PAC_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('no_expediente', models.CharField(db_column='NO_EXPEDIENTE', max_length=30)),
                ('primer_nombre', models.CharField(db_column='PRIMER_NOMBRE', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, db_column='SEGUNDO_NOMBRE', default='', max_length=100)),
                ('primer_apellido', models.CharField(db_column='PRIMER_APELLIDO', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, db_column='SEGUNDO_APELLIDO', default='', max_length=100)),
                ('nombre_casada', models.CharField(blank=True, db_column='NOMBRE_CASADA', default='', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DPI', 'DPI'), ('PASAPORTE', 'Pasaporte'), ('CUI', 'CUI'), ('CEDULA', 'Cedula'), ('OTRO', 'Otro')], db_column='TIPO_DOCUMENTO', max_length=20)),
                ('no_documento', models.CharField(db_column='NO_DOCUMENTO', max_length=30)),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='SEXO', max_length=1)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('UNION_LIBRE', 'Union Libre'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], db_column='ESTADO_CIVIL', default='SOLTERO', max_length=20)),
                ('nacionalidad', models.CharField(db_column='NACIONALIDAD', default='GUATEMALTECA', max_length=50)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', default='', max_length=500)),
                ('municipio', models.CharField(blank=True, db_column='MUNICIPIO', default='', max_length=100)),
                ('departamento', models.CharField(blank=True, db_column='DEPARTAMENTO', default='', max_length=100)),
                ('telefono_principal', models.CharField(blank=True, db_column='TELEFONO_PRINCIPAL', default='', max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, db_column='TELEFONO_ALTERNATIVO', default='', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', default='', max_length=150)),
                ('tipo_paciente', models.CharField(choices=[('GENERAL', 'General'), ('IGSS', 'IGSS'), ('PRIVADO', 'Privado'), ('SEGURO', 'Seguro Medico'), ('EXTERIOR', 'Exterior'), ('OTRO', 'Otro')], db_column='TIPO_PACIENTE', default='GENERAL', max_length=30)),
                ('no_afiliacion', models.CharField(blank=True, db_column='NO_AFILIACION', default='', max_length=50)),
                ('aseguradora', models.CharField(blank=True, db_column='ASEGURADORA', default='', max_length=100)),
                ('grupo_sanguineo', models.CharField(blank=True, db_column='GRUPO_SANGUINEO', default='', max_length=5)),
                ('factor_rh', models.CharField(blank=True, db_column='FACTOR_RH', default='', max_length=1)),
                ('peso_kg', models.DecimalField(blank=True, db_column='PESO_KG', decimal_places=2, max_digits=5, null=True)),
                ('talla_cm', models.DecimalField(blank=True, db_column='TALLA_CM', decimal_places=1, max_digits=5, null=True)),
                ('foto_s3_key', models.CharField(blank=True, db_column='FOTO_S3_KEY', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_column='MEDICO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'PAC_PACIENTES',
                'ordering': ['primer_apellido', 'primer_nombre'],
                'unique_together': {('hospital_id', 'no_expediente'), ('hospital_id', 'tipo_documento', 'no_documento')},
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('historial_id', models.AutoField(db_column='HISTORIAL_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('tipo_entrada', models.CharField(choices=[('CONSULTA', 'Consulta'), ('HOSPITALIZACION', 'Hospitalizacion'), ('CIRUGIA', 'Cirugia'), ('LABORATORIO', 'Laboratorio'), ('IMAGEN', 'Imagen / Radiologia'), ('MEDICAMENTO', 'Medicamento'), ('VACUNA', 'Vacuna'), ('OTRO', 'Otro')], db_column='TIPO_ENTRADA', max_length=50)),
                ('titulo', models.CharField(db_column='TITULO', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', default='')),
                ('diagnostico_cie10', models.CharField(blank=True, db_column='DIAGNOSTICO_CIE10', default='', max_length=10)),
                ('fecha_evento', models.DateField(db_column='FECHA_EVENTO')),
                ('es_privado', models.BooleanField(db_column='ES_PRIVADO', default=False)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_creado', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_column='MEDICO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_registrado', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_actualizado', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='patients.paciente')),
            ],
            options={
                'verbose_name': 'Historial Clinico',
                'verbose_name_plural': 'Historial Clinico',
                'db_table': 'PAC_HISTORIAL_CLINICO',
                'ordering': ['-fecha_evento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('contacto_id', models.AutoField(db_column='CONTACTO_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('nombre_completo', models.CharField(db_column='NOMBRE_COMPLETO', max_length=200)),
                ('parentesco', models.CharField(db_column='PARENTESCO', max_length=50)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20)),
                ('telefono_alt', models.CharField(blank=True, db_column='TELEFONO_ALT', default='', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', default='', max_length=150)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', default='', max_length=500)),
                ('es_responsable', models.BooleanField(db_column='ES_RESPONSABLE', default=False)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='patients.paciente')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
                'db_table': 'PAC_CONTACTOS_EMERGENCIA',
                'ordering': ['-es_responsable', 'nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('alergia_id', models.AutoField(db_column='ALERGIA_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('tipo_alergia', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('ALIMENTO', 'Alimento'), ('AMBIENTAL', 'Ambiental'), ('LATEX', 'Latex'), ('OTRO', 'Otro')], db_column='TIPO_ALERGIA', max_length=50)),
                ('agente', models.CharField(db_column='AGENTE', max_length=200)),
                ('reaccion', models.CharField(blank=True, db_column='REACCION', default='', max_length=500)),
                ('severidad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa'), ('ANAFILACTICA', 'Anafila ctica')], db_column='SEVERIDAD', default='MODERADA', max_length=20)),
                ('verificada', models.BooleanField(db_column='VERIFICADA', default=False)),
                ('fecha_deteccion', models.DateField(blank=True, db_column='FECHA_DETECCION', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='OBSERVACIONES', default='', max_length=1000)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alergias_registradas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alergias_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='patients.paciente')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'db_table': 'PAC_ALERGIAS',
                'ordering': ['severidad', 'agente'],
            },
        ),
    ]
