-- ============================================================
-- HealthTech Solutions — Sequences Módulo Seguridad (SEC)
-- CACHE 50: evita contención en Oracle 19c RAC (ambos nodos)
-- NOORDER: aceptable para PKs — no requieren orden estricto
-- Compatible: Oracle 19c RAC y Oracle 21c XE
-- ============================================================

-- Hospitales
BEGIN
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_SEC_HOSPITALES
     START WITH 1 INCREMENT BY 1
     CACHE 50 NOORDER NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Roles
BEGIN
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_SEC_ROLES
     START WITH 1 INCREMENT BY 1
     CACHE 50 NOORDER NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Permisos
BEGIN
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_SEC_PERMISOS
     START WITH 1 INCREMENT BY 1
     CACHE 50 NOORDER NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Usuarios
BEGIN
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_SEC_USUARIOS
     START WITH 1 INCREMENT BY 1
     CACHE 50 NOORDER NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Sesiones
BEGIN
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_SEC_SESIONES
     START WITH 1 INCREMENT BY 1
     CACHE 50 NOORDER NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Auditoría de accesos
BEGIN
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_SEC_AUDITORIA
     START WITH 1 INCREMENT BY 1
     CACHE 100 NOORDER NOCYCLE';    -- Cache mayor: tabla de alta escritura
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT ✅ Sequences SEC creadas correctamente.
