# Generated by Django 5.2.4 on 2026-03-06 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('emergency', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('cama_id', models.AutoField(db_column='CAMA_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('numero_cama', models.CharField(db_column='NUMERO_CAMA', max_length=10)),
                ('piso', models.CharField(blank=True, db_column='PISO', default='', max_length=10)),
                ('sala', models.CharField(blank=True, db_column='SALA', default='', max_length=50)),
                ('tipo_cama', models.CharField(choices=[('GENERAL', 'General'), ('UCI', 'UCI / Cuidados Intensivos'), ('PEDIATRICA', 'Pediátrica'), ('MATERNIDAD', 'Maternidad'), ('CIRUGIA', 'Cirugía'), ('AISLAMIENTO', 'Aislamiento'), ('OBSERVACION', 'Observación')], db_column='TIPO_CAMA', max_length=30)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('MANTENIMIENTO', 'En Mantenimiento')], db_column='ESTADO', default='DISPONIBLE', max_length=20)),
                ('tiene_oxigeno', models.BooleanField(db_column='TIENE_OXIGENO', default=False)),
                ('tiene_monitor', models.BooleanField(db_column='TIENE_MONITOR', default=False)),
                ('tiene_ventilador', models.BooleanField(db_column='TIENE_VENTILADOR', default=False)),
                ('observaciones', models.CharField(blank=True, db_column='OBSERVACIONES', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'verbose_name': 'Cama',
                'verbose_name_plural': 'Camas',
                'db_table': 'ENC_CAMAS',
                'ordering': ['sala', 'piso', 'numero_cama'],
                'unique_together': {('hospital_id', 'numero_cama')},
            },
        ),
        migrations.CreateModel(
            name='Encamamiento',
            fields=[
                ('enc_id', models.AutoField(db_column='ENC_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('fecha_ingreso', models.DateField(db_column='FECHA_INGRESO')),
                ('hora_ingreso', models.TimeField(db_column='HORA_INGRESO')),
                ('motivo_ingreso', models.CharField(db_column='MOTIVO_INGRESO', max_length=500)),
                ('diagnostico_ingreso', models.CharField(blank=True, db_column='DIAGNOSTICO_INGRESO', default='', max_length=500)),
                ('cie10_ingreso', models.CharField(blank=True, db_column='CIE10_INGRESO', default='', max_length=10)),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_TRATAMIENTO', 'En Tratamiento'), ('EGRESADO', 'Egresado'), ('TRASLADADO', 'Trasladado'), ('FALLECIDO', 'Fallecido')], db_column='ESTADO', default='INGRESADO', max_length=30)),
                ('notas_ingreso', models.TextField(blank=True, db_column='NOTAS_INGRESO', default='')),
                ('evolucion', models.TextField(blank=True, db_column='EVOLUCION', default='')),
                ('indicaciones', models.TextField(blank=True, db_column='INDICACIONES', default='')),
                ('tipo_egreso', models.CharField(blank=True, choices=[('ALTA_MEDICA', 'Alta Médica'), ('VOLUNTARIA', 'Voluntaria'), ('TRASLADO', 'Traslado'), ('FALLECIMIENTO', 'Fallecimiento'), ('FUGA', 'Fuga')], db_column='TIPO_EGRESO', default='', max_length=30)),
                ('fecha_egreso', models.DateField(blank=True, db_column='FECHA_EGRESO', null=True)),
                ('hora_egreso', models.TimeField(blank=True, db_column='HORA_EGRESO', null=True)),
                ('diagnostico_egreso', models.CharField(blank=True, db_column='DIAGNOSTICO_EGRESO', default='', max_length=500)),
                ('cie10_egreso', models.CharField(blank=True, db_column='CIE10_EGRESO', default='', max_length=10)),
                ('destino_egreso', models.CharField(blank=True, db_column='DESTINO_EGRESO', default='', max_length=200)),
                ('dias_estancia', models.SmallIntegerField(blank=True, db_column='DIAS_ESTANCIA', null=True)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('cama', models.ForeignKey(db_column='CAMA_ID', on_delete=django.db.models.deletion.PROTECT, related_name='encamamientos', to='hospitalization.cama')),
                ('cita', models.ForeignKey(blank=True, db_column='CIT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encamamientos', to='appointments.cita')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encamamientos_creados', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(blank=True, db_column='EMG_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encamamientos', to='emergency.emergencia')),
                ('enfermero', models.ForeignKey(blank=True, db_column='ENFERMERO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encamamientos_enfermero', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(db_column='MEDICO_ID', on_delete=django.db.models.deletion.PROTECT, related_name='encamamientos_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='encamamientos', to='patients.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encamamientos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encamamiento',
                'verbose_name_plural': 'Encamamientos',
                'db_table': 'ENC_ENCAMAMIENTOS',
                'ordering': ['-fecha_ingreso', '-hora_ingreso'],
            },
        ),
    ]
