# Generated by Django 5.2.4 on 2026-03-06 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('cir_id', models.AutoField(db_column='CIR_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('fecha_programada', models.DateField(db_column='FECHA_PROGRAMADA')),
                ('hora_ini_prog', models.TimeField(db_column='HORA_INI_PROG')),
                ('hora_fin_prog', models.TimeField(blank=True, db_column='HORA_FIN_PROG', null=True)),
                ('duracion_est_min', models.SmallIntegerField(blank=True, db_column='DURACION_EST_MIN', null=True)),
                ('quirofano', models.CharField(db_column='QUIROFANO', max_length=30)),
                ('tipo_cirugia', models.CharField(db_column='TIPO_CIRUGIA', max_length=200)),
                ('especialidad', models.CharField(blank=True, db_column='ESPECIALIDAD', default='', max_length=100)),
                ('prioridad', models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('URGENTE', 'Urgente'), ('ELECTIVA', 'Electiva')], db_column='PRIORIDAD', default='ELECTIVA', max_length=20)),
                ('tipo_anestesia', models.CharField(choices=[('GENERAL', 'General'), ('REGIONAL', 'Regional'), ('LOCAL', 'Local'), ('SEDACION', 'Sedación'), ('NINGUNA', 'Ninguna')], db_column='TIPO_ANESTESIA', default='GENERAL', max_length=30)),
                ('cie10_pre', models.CharField(blank=True, db_column='CIE10_PRE', default='', max_length=10)),
                ('diagnostico_preop', models.CharField(blank=True, db_column='DIAGNOSTICO_PREOP', default='', max_length=500)),
                ('notas_preop', models.TextField(blank=True, db_column='NOTAS_PREOP', default='')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], db_column='ESTADO', default='PROGRAMADA', max_length=30)),
                ('fecha_inicio_real', models.DateField(blank=True, db_column='FECHA_INICIO_REAL', null=True)),
                ('hora_inicio_real', models.TimeField(blank=True, db_column='HORA_INICIO_REAL', null=True)),
                ('fecha_fin_real', models.DateField(blank=True, db_column='FECHA_FIN_REAL', null=True)),
                ('hora_fin_real', models.TimeField(blank=True, db_column='HORA_FIN_REAL', null=True)),
                ('duracion_real_min', models.SmallIntegerField(blank=True, db_column='DURACION_REAL_MIN', null=True)),
                ('hallazgos', models.TextField(blank=True, db_column='HALLAZGOS', default='')),
                ('complicaciones', models.CharField(blank=True, db_column='COMPLICACIONES', default='', max_length=500)),
                ('notas_postop', models.TextField(blank=True, db_column='NOTAS_POSTOP', default='')),
                ('diagnostico_postop', models.CharField(blank=True, db_column='DIAGNOSTICO_POSTOP', default='', max_length=500)),
                ('cie10_post', models.CharField(blank=True, db_column='CIE10_POST', default='', max_length=10)),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='MOTIVO_CANCELACION', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('anestesiologo', models.ForeignKey(blank=True, db_column='ANESTESIOLOGO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_como_anestesiologo', to=settings.AUTH_USER_MODEL)),
                ('cirujano', models.ForeignKey(db_column='CIRUJANO_ID', on_delete=django.db.models.deletion.PROTECT, related_name='cirugias_como_cirujano', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_creadas', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(blank=True, db_column='EMG_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias', to='emergency.emergencia')),
                ('encamamiento', models.ForeignKey(blank=True, db_column='ENC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias', to='hospitalization.encamamiento')),
                ('enfermero_circ', models.ForeignKey(blank=True, db_column='ENFERMERO_CIRC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_como_enfermero_circ', to=settings.AUTH_USER_MODEL)),
                ('enfermero_inst', models.ForeignKey(blank=True, db_column='ENFERMERO_INST_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_como_enfermero_inst', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='cirugias', to='patients.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'db_table': 'CIR_CIRUGIAS',
                'ordering': ['fecha_programada', 'hora_ini_prog'],
            },
        ),
    ]
