# Generated by Django 5.2.4 on 2026-03-06 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('emg_id', models.AutoField(db_column='EMG_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('fecha_ingreso', models.DateField(db_column='FECHA_INGRESO')),
                ('hora_ingreso', models.TimeField(db_column='HORA_INGRESO')),
                ('motivo_consulta', models.CharField(db_column='MOTIVO_CONSULTA', max_length=500)),
                ('nivel_triaje', models.CharField(choices=[('ROJO', 'Rojo — Inmediato'), ('NARANJA', 'Naranja — Muy urgente'), ('AMARILLO', 'Amarillo — Urgente'), ('VERDE', 'Verde — Poco urgente'), ('AZUL', 'Azul — No urgente')], db_column='NIVEL_TRIAJE', max_length=20)),
                ('presion_sistolica', models.SmallIntegerField(blank=True, db_column='PRESION_SISTOLICA', null=True)),
                ('presion_diastolica', models.SmallIntegerField(blank=True, db_column='PRESION_DIASTOLICA', null=True)),
                ('frecuencia_cardiaca', models.SmallIntegerField(blank=True, db_column='FRECUENCIA_CARDIACA', null=True)),
                ('frecuencia_resp', models.SmallIntegerField(blank=True, db_column='FRECUENCIA_RESP', null=True)),
                ('temperatura', models.DecimalField(blank=True, db_column='TEMPERATURA', decimal_places=1, max_digits=4, null=True)),
                ('saturacion_o2', models.SmallIntegerField(blank=True, db_column='SATURACION_O2', null=True)),
                ('glucosa', models.SmallIntegerField(blank=True, db_column='GLUCOSA', null=True)),
                ('peso_kg', models.DecimalField(blank=True, db_column='PESO_KG', decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('ESPERA', 'En Espera'), ('EN_ATENCION', 'En Atención'), ('OBSERVACION', 'En Observación'), ('ALTA', 'Alta'), ('TRANSFERIDO', 'Transferido'), ('FALLECIDO', 'Fallecido')], db_column='ESTADO', default='ESPERA', max_length=30)),
                ('diagnostico', models.CharField(blank=True, db_column='DIAGNOSTICO', default='', max_length=500)),
                ('cie10_codigo', models.CharField(blank=True, db_column='CIE10_CODIGO', default='', max_length=10)),
                ('tratamiento', models.TextField(blank=True, db_column='TRATAMIENTO', default='')),
                ('notas_medico', models.TextField(blank=True, db_column='NOTAS_MEDICO', default='')),
                ('notas_enfermero', models.CharField(blank=True, db_column='NOTAS_ENFERMERO', default='', max_length=1000)),
                ('tipo_alta', models.CharField(blank=True, choices=[('VOLUNTARIA', 'Voluntaria'), ('MEDICA', 'Alta Médica'), ('FUGA', 'Fuga'), ('FALLECIMIENTO', 'Fallecimiento'), ('TRANSFERENCIA', 'Transferencia')], db_column='TIPO_ALTA', default='', max_length=30)),
                ('fecha_alta', models.DateField(blank=True, db_column='FECHA_ALTA', null=True)),
                ('hora_alta', models.TimeField(blank=True, db_column='HORA_ALTA', null=True)),
                ('destino_alta', models.CharField(blank=True, db_column='DESTINO_ALTA', default='', max_length=200)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('enfermero', models.ForeignKey(blank=True, db_column='ENFERMERO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_triaje', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_column='MEDICO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_atendidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='emergencias', to='patients.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergencia',
                'verbose_name_plural': 'Emergencias',
                'db_table': 'EMG_EMERGENCIAS',
                'ordering': ['-fecha_ingreso', '-hora_ingreso'],
            },
        ),
    ]
