# Generated by Django 5.2.4 on 2026-03-06 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('emergency', '0001_initial'),
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('med_id', models.AutoField(db_column='MED_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('nombre_generico', models.CharField(db_column='NOMBRE_GENERICO', max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, db_column='NOMBRE_COMERCIAL', default='', max_length=200)),
                ('principio_activo', models.CharField(blank=True, db_column='PRINCIPIO_ACTIVO', default='', max_length=200)),
                ('concentracion', models.CharField(blank=True, db_column='CONCENTRACION', default='', max_length=100)),
                ('forma_farma', models.CharField(choices=[('TABLETA', 'Tableta'), ('CAPSULA', 'Cápsula'), ('JARABE', 'Jarabe'), ('INYECTABLE', 'Inyectable'), ('CREMA', 'Crema'), ('SOLUCION', 'Solución'), ('SUPOSITORIO', 'Supositorio'), ('GOTAS', 'Gotas'), ('PARCHE', 'Parche'), ('OTRO', 'Otro')], db_column='FORMA_FARMA', default='TABLETA', max_length=30)),
                ('categoria', models.CharField(choices=[('ANALGESICO', 'Analgésico'), ('ANTIBIOTICO', 'Antibiótico'), ('ANTIHIPERTENSIVO', 'Antihipertensivo'), ('ANTIDIABETICO', 'Antidiabético'), ('VITAMINA', 'Vitamina / Suplemento'), ('ANTIINFLAMATORIO', 'Antiinflamatorio'), ('CARDIOVASCULAR', 'Cardiovascular'), ('NEUROLOGICO', 'Neurológico'), ('RESPIRATORIO', 'Respiratorio'), ('OTRO', 'Otro')], db_column='CATEGORIA', default='OTRO', max_length=50)),
                ('unidad_medida', models.CharField(db_column='UNIDAD_MEDIDA', default='tableta', max_length=30)),
                ('stock_actual', models.IntegerField(db_column='STOCK_ACTUAL', default=0)),
                ('stock_minimo', models.IntegerField(db_column='STOCK_MINIMO', default=10)),
                ('precio_unitario', models.DecimalField(db_column='PRECIO_UNITARIO', decimal_places=2, default=0, max_digits=10)),
                ('requiere_receta', models.BooleanField(db_column='REQUIERE_RECETA', default=False)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'FAR_MEDICAMENTOS',
                'ordering': ['nombre_generico'],
            },
        ),
        migrations.CreateModel(
            name='Dispensacion',
            fields=[
                ('dis_id', models.AutoField(db_column='DIS_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('cantidad', models.DecimalField(db_column='CANTIDAD', decimal_places=3, max_digits=10)),
                ('dosis', models.CharField(blank=True, db_column='DOSIS', default='', max_length=200)),
                ('frecuencia', models.CharField(blank=True, db_column='FRECUENCIA', default='', max_length=100)),
                ('duracion_dias', models.SmallIntegerField(blank=True, db_column='DURACION_DIAS', null=True)),
                ('via_admin', models.CharField(choices=[('ORAL', 'Oral'), ('INTRAVENOSA', 'Intravenosa'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutánea'), ('TOPICA', 'Tópica'), ('INHALATORIA', 'Inhalatoria'), ('SUBLINGUAL', 'Sublingual'), ('RECTAL', 'Rectal'), ('NASAL', 'Nasal'), ('OFTALMICA', 'Oftálmica'), ('OTICA', 'Ótica'), ('OTRO', 'Otro')], db_column='VIA_ADMIN', default='ORAL', max_length=30)),
                ('indicaciones', models.CharField(blank=True, db_column='INDICACIONES', default='', max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DISPENSADA', 'Dispensada'), ('CANCELADA', 'Cancelada')], db_column='ESTADO', default='PENDIENTE', max_length=20)),
                ('fecha_prescripcion', models.DateField(db_column='FECHA_PRESCRIPCION')),
                ('fecha_dispensacion', models.DateField(blank=True, db_column='FECHA_DISPENSACION', null=True)),
                ('hora_dispensacion', models.TimeField(blank=True, db_column='HORA_DISPENSACION', null=True)),
                ('notas_farmacia', models.CharField(blank=True, db_column='NOTAS_FARMACIA', default='', max_length=1000)),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='MOTIVO_CANCELACION', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('cita', models.ForeignKey(blank=True, db_column='CIT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones', to='appointments.cita')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('dispensado_por', models.ForeignKey(blank=True, db_column='DISPENSADO_POR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(blank=True, db_column='EMG_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones', to='emergency.emergencia')),
                ('encamamiento', models.ForeignKey(blank=True, db_column='ENC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones', to='hospitalization.encamamiento')),
                ('medico_prescribe', models.ForeignKey(blank=True, db_column='MEDICO_PRES_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones_prescritas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='dispensaciones', to='patients.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.ForeignKey(db_column='MED_ID', on_delete=django.db.models.deletion.PROTECT, related_name='dispensaciones', to='pharmacy.medicamento')),
            ],
            options={
                'verbose_name': 'Dispensación',
                'verbose_name_plural': 'Dispensaciones',
                'db_table': 'FAR_DISPENSACIONES',
                'ordering': ['-fecha_prescripcion', '-created_at'],
            },
        ),
    ]
