# Generated by Django 5.2.4 on 2026-03-07 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('emergency', '0001_initial'),
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioImagen',
            fields=[
                ('est_id', models.AutoField(db_column='EST_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('modalidad', models.CharField(choices=[('XRAY', 'Rayos X'), ('CT', 'Tomografía Computarizada (CT/TAC)'), ('MRI', 'Resonancia Magnética (MRI/RMN)'), ('ULTRASONIDO', 'Ultrasonido / Ecografía'), ('MAMMOGRAFIA', 'Mamografía'), ('PET', 'PET Scan'), ('ANGIOGRAFIA', 'Angiografía'), ('FLUOROSCOPIA', 'Fluoroscopía'), ('DENSITOMETRIA', 'Densitometría Ósea'), ('OTRO', 'Otro')], db_column='MODALIDAD', max_length=30)),
                ('region_anatomica', models.CharField(choices=[('CRANEO', 'Cráneo / Cerebro'), ('TORAX', 'Tórax'), ('ABDOMEN', 'Abdomen'), ('COLUMNA', 'Columna Vertebral'), ('EXTREMIDADES', 'Extremidades'), ('PELVIS', 'Pelvis'), ('CORAZON', 'Corazón / Cardiovascular'), ('CUELLO', 'Cuello'), ('MAMA', 'Mama'), ('CUERPO_ENTERO', 'Cuerpo Entero'), ('OTRO', 'Otro')], db_column='REGION_ANATOMICA', default='OTRO', max_length=30)),
                ('descripcion_clinica', models.CharField(db_column='DESCRIPCION_CLINICA', max_length=500)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia')], db_column='PRIORIDAD', default='NORMAL', max_length=20)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_column='ESTADO', default='SOLICITADO', max_length=20)),
                ('fecha_solicitud', models.DateField(db_column='FECHA_SOLICITUD')),
                ('fecha_realizacion', models.DateField(blank=True, db_column='FECHA_REALIZACION', null=True)),
                ('fecha_informe', models.DateField(blank=True, db_column='FECHA_INFORME', null=True)),
                ('s3_bucket', models.CharField(blank=True, db_column='S3_BUCKET', default='', max_length=100)),
                ('s3_prefix', models.CharField(blank=True, db_column='S3_PREFIX', default='', max_length=500)),
                ('num_imagenes', models.PositiveSmallIntegerField(db_column='NUM_IMAGENES', default=0)),
                ('informe', models.TextField(blank=True, db_column='INFORME', default='')),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='MOTIVO_CANCELACION', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('cita', models.ForeignKey(blank=True, db_column='CIT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_imagen', to='appointments.cita')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_creados', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(blank=True, db_column='EMG_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_imagen', to='emergency.emergencia')),
                ('encamamiento', models.ForeignKey(blank=True, db_column='ENC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_imagen', to='hospitalization.encamamiento')),
                ('medico_sol', models.ForeignKey(db_column='MEDICO_SOL_ID', on_delete=django.db.models.deletion.PROTECT, related_name='estudios_solicitados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='estudios_imagen', to='patients.paciente')),
                ('radiologo', models.ForeignKey(blank=True, db_column='RADIOLOGO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_informados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, db_column='TECNICO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_realizados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio de Imagen',
                'verbose_name_plural': 'Estudios de Imagen',
                'db_table': 'IMG_ESTUDIOS',
                'ordering': ['-fecha_solicitud', '-created_at'],
            },
        ),
    ]
