# Generated by Django 5.2.4 on 2026-03-06 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEnfermeria',
            fields=[
                ('nota_id', models.AutoField(db_column='NOTA_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('tipo_nota', models.CharField(choices=[('EVOLUCION', 'Evolución de Enfermería'), ('PROCEDIMIENTO', 'Procedimiento'), ('MEDICAMENTO', 'Administración de Medicamento'), ('INCIDENTE', 'Incidente / Evento Adverso'), ('INGRESO', 'Nota de Ingreso'), ('EGRESO', 'Nota de Egreso'), ('OTRO', 'Otro')], db_column='TIPO_NOTA', default='EVOLUCION', max_length=30)),
                ('contenido', models.TextField(db_column='CONTENIDO')),
                ('es_urgente', models.BooleanField(db_column='ES_URGENTE', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_enfermeria_creadas', to=settings.AUTH_USER_MODEL)),
                ('encamamiento', models.ForeignKey(blank=True, db_column='ENC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_enfermeria', to='hospitalization.encamamiento')),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='notas_enfermeria', to='patients.paciente')),
            ],
            options={
                'verbose_name': 'Nota de Enfermería',
                'verbose_name_plural': 'Notas de Enfermería',
                'db_table': 'ENF_NOTAS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('sig_id', models.AutoField(db_column='SIG_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('temperatura', models.DecimalField(blank=True, db_column='TEMPERATURA', decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, db_column='PRESION_SISTOLICA', help_text='mmHg', null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, db_column='PRESION_DIASTOLICA', help_text='mmHg', null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, db_column='FRECUENCIA_CARDIACA', help_text='bpm', null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, db_column='FRECUENCIA_RESPIRATORIA', help_text='rpm', null=True)),
                ('saturacion_o2', models.DecimalField(blank=True, db_column='SATURACION_O2', decimal_places=2, help_text='%', max_digits=5, null=True)),
                ('glucemia', models.DecimalField(blank=True, db_column='GLUCEMIA', decimal_places=1, help_text='mg/dL', max_digits=6, null=True)),
                ('peso', models.DecimalField(blank=True, db_column='PESO', decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, db_column='TALLA', decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('glasgow', models.IntegerField(blank=True, db_column='GLASGOW', help_text='3-15', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='OBSERVACIONES', default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_registrados', to=settings.AUTH_USER_MODEL)),
                ('encamamiento', models.ForeignKey(blank=True, db_column='ENC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_vitales', to='hospitalization.encamamiento')),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='signos_vitales', to='patients.paciente')),
            ],
            options={
                'verbose_name': 'Signo Vital',
                'verbose_name_plural': 'Signos Vitales',
                'db_table': 'ENF_SIGNOS_VITALES',
                'ordering': ['-created_at'],
            },
        ),
    ]
