# Generated by Django 5.2.4 on 2026-03-06 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('emergency', '0001_initial'),
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenLab',
            fields=[
                ('lab_id', models.AutoField(db_column='LAB_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('fecha_solicitud', models.DateField(db_column='FECHA_SOLICITUD')),
                ('hora_solicitud', models.TimeField(db_column='HORA_SOLICITUD')),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia')], db_column='PRIORIDAD', default='NORMAL', max_length=20)),
                ('tipo_muestra', models.CharField(choices=[('SANGRE', 'Sangre'), ('ORINA', 'Orina'), ('HECES', 'Heces'), ('ESPUTO', 'Esputo'), ('LCR', 'Líquido Cefalorraquídeo'), ('TEJIDO', 'Tejido / Biopsia'), ('HISOPADO', 'Hisopado'), ('OTRO', 'Otro')], db_column='TIPO_MUESTRA', default='SANGRE', max_length=30)),
                ('grupo_examen', models.CharField(blank=True, db_column='GRUPO_EXAMEN', default='', max_length=30)),
                ('examenes_solicitados', models.CharField(db_column='EXAMENES_SOLICITADOS', max_length=2000)),
                ('observaciones_clin', models.CharField(blank=True, db_column='OBSERVACIONES_CLIN', default='', max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_column='ESTADO', default='PENDIENTE', max_length=30)),
                ('fecha_muestra', models.DateField(blank=True, db_column='FECHA_MUESTRA', null=True)),
                ('hora_muestra', models.TimeField(blank=True, db_column='HORA_MUESTRA', null=True)),
                ('fecha_resultado', models.DateField(blank=True, db_column='FECHA_RESULTADO', null=True)),
                ('hora_resultado', models.TimeField(blank=True, db_column='HORA_RESULTADO', null=True)),
                ('notas_laboratorio', models.CharField(blank=True, db_column='NOTAS_LABORATORIO', default='', max_length=1000)),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='MOTIVO_CANCELACION', default='', max_length=500)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('cita', models.ForeignKey(blank=True, db_column='CIT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab', to='appointments.cita')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab_creadas', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(blank=True, db_column='EMG_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab', to='emergency.emergencia')),
                ('encamamiento', models.ForeignKey(blank=True, db_column='ENC_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab', to='hospitalization.encamamiento')),
                ('laboratorista', models.ForeignKey(blank=True, db_column='LABORATORISTA_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab_procesadas', to=settings.AUTH_USER_MODEL)),
                ('medico_solic', models.ForeignKey(db_column='MEDICO_SOLIC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_lab_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='PAC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_lab', to='patients.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Laboratorio',
                'verbose_name_plural': 'Órdenes de Laboratorio',
                'db_table': 'LAB_ORDENES',
                'ordering': ['-fecha_solicitud', '-hora_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLab',
            fields=[
                ('res_id', models.AutoField(db_column='RES_ID', primary_key=True, serialize=False)),
                ('hospital_id', models.IntegerField(db_column='HOSPITAL_ID')),
                ('nombre_examen', models.CharField(db_column='NOMBRE_EXAMEN', max_length=200)),
                ('valor', models.CharField(db_column='VALOR', max_length=500)),
                ('unidad', models.CharField(blank=True, db_column='UNIDAD', default='', max_length=50)),
                ('rango_min', models.CharField(blank=True, db_column='RANGO_MIN', default='', max_length=100)),
                ('rango_max', models.CharField(blank=True, db_column='RANGO_MAX', default='', max_length=100)),
                ('valor_referencia', models.CharField(blank=True, db_column='VALOR_REFERENCIA', default='', max_length=200)),
                ('interpretacion', models.CharField(blank=True, db_column='INTERPRETACION', default='', max_length=500)),
                ('estado_resultado', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTO', 'Alto'), ('BAJO', 'Bajo'), ('CRITICO', 'Crítico'), ('PENDIENTE', 'Pendiente')], db_column='ESTADO_RESULTADO', default='NORMAL', max_length=20)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_lab_creados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(db_column='LAB_ID', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='laboratory.ordenlab')),
            ],
            options={
                'verbose_name': 'Resultado de Laboratorio',
                'verbose_name_plural': 'Resultados de Laboratorio',
                'db_table': 'LAB_RESULTADOS',
                'ordering': ['nombre_examen'],
            },
        ),
    ]
